"use client"

import React, { useEffect, useId, useMemo, useRef, useState } from "react"
import { ArrowLeft, CircleAlert, ExternalLink, FilePlus2, Loader2, Plus, Save, Send, Trash2 } from "lucide-react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"

import { useAuth } from "@/components/auth/AuthProvider"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { ApiClientError } from "@/lib/api/client"
import { clearRemitoWorkspaceDraft, readRemitoWorkspaceDraft, writeRemitoWorkspaceDraft, type RemitoWorkspaceDraftContext } from "@/lib/remito-workspace-draft-recovery"
import {
  createRemito, emitirRemito, fetchRemito, fetchRemitoDevPreset, REMITO_ORIGINS, REMITO_SALIDA_REASONS,
  type CreateRemitoPayload, type RemitoApiRow, type RemitoDevPreset, type RemitoOrigin, type RemitoSalidaReason,
  type UpdateRemitoDraftPayload, updateRemitoDraft,
} from "@/lib/api/remitos"

type DraftItem = { itemId?: string; sku: string; description: string; quantity: string; unit: string; boxId?: string; presupuestoItemId?: string; lotNumber: string; serialNumber: string; expirationDate: string; metadata?: Record<string, unknown> }
type Draft = { origin: RemitoOrigin; salidaReason: RemitoSalidaReason; branchId: string; issuedBranchId: string; surgeryId: string; boxId: string; presupuestoId: string; destinatarioContactId: string; destinatarioNombre: string; domicilio: string; localidad: string; provincia: string; transporte: string; packageCount: string; declaredValue: string; observaciones: string; destinatarioSnapshot: Record<string, unknown> | null; shippingAddressSnapshot: Record<string, unknown> | null; transportSnapshot: Record<string, unknown> | null; metadata: Record<string, unknown> | null; items: DraftItem[] }
type RecoveryDraft = Omit<Draft, "destinatarioSnapshot" | "shippingAddressSnapshot" | "transportSnapshot" | "metadata" | "items"> & { items: Array<Omit<DraftItem, "metadata">> }
type Errors = Record<string, string>

const emptyItem = (): DraftItem => ({ sku: "", description: "", quantity: "1", unit: "unidad", lotNumber: "", serialNumber: "", expirationDate: "" })
const emptyDraft = (): Draft => ({ origin: "manual", salidaReason: "cirugia", branchId: "", issuedBranchId: "", surgeryId: "", boxId: "", presupuestoId: "", destinatarioContactId: "", destinatarioNombre: "", domicilio: "", localidad: "", provincia: "", transporte: "", packageCount: "", declaredValue: "", observaciones: "", destinatarioSnapshot: null, shippingAddressSnapshot: null, transportSnapshot: null, metadata: null, items: [emptyItem()] })

// Recovery intentionally keeps only explicit form fields; opaque server snapshots and metadata remain server-owned.
function recoveryDraft(draft: Draft): RecoveryDraft {
  const { destinatarioSnapshot: _destinatarioSnapshot, shippingAddressSnapshot: _shippingAddressSnapshot, transportSnapshot: _transportSnapshot, metadata: _metadata, ...editable } = draft
  return { ...editable, items: draft.items.map(({ metadata: _itemMetadata, ...item }) => ({ ...item })) }
}
function isRecoveryDraft(value: unknown): value is RecoveryDraft {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false
  const draft = value as Record<string, unknown>
  const scalarKeys: Array<keyof Draft> = ["origin", "salidaReason", "branchId", "issuedBranchId", "surgeryId", "boxId", "presupuestoId", "destinatarioContactId", "destinatarioNombre", "domicilio", "localidad", "provincia", "transporte", "packageCount", "declaredValue", "observaciones"]
  if (scalarKeys.some((key) => typeof draft[key] !== "string") || !Array.isArray(draft.items)) return false
  return draft.items.every((item) => item && typeof item === "object" && ["sku", "description", "quantity", "unit", "lotNumber", "serialNumber", "expirationDate"].every((key) => typeof (item as Record<string, unknown>)[key] === "string"))
}

function fromRemito(remito: RemitoApiRow): Draft {
  return { origin: REMITO_ORIGINS.includes(remito.origin as RemitoOrigin) ? remito.origin as RemitoOrigin : "manual", salidaReason: REMITO_SALIDA_REASONS.includes(remito.salidaReason as RemitoSalidaReason) ? remito.salidaReason as RemitoSalidaReason : "cirugia", branchId: remito.branchId ?? "", issuedBranchId: remito.issuedBranchId ?? remito.branchId ?? "", surgeryId: remito.surgeryId ?? "", boxId: remito.boxId ?? "", presupuestoId: remito.presupuestoId ?? "", destinatarioContactId: remito.destinatarioContactId ?? "", destinatarioNombre: remito.destinatarioSnapshot?.nombre ?? "", domicilio: remito.shippingAddressSnapshot?.domicilio ?? remito.destinatarioSnapshot?.domicilio ?? "", localidad: remito.shippingAddressSnapshot?.localidad ?? remito.destinatarioSnapshot?.localidad ?? "", provincia: remito.shippingAddressSnapshot?.provincia ?? remito.destinatarioSnapshot?.provincia ?? "", transporte: typeof remito.transportSnapshot?.nombre === "string" ? remito.transportSnapshot.nombre : "", packageCount: remito.packageCount == null ? "" : String(remito.packageCount), declaredValue: remito.declaredValue == null ? "" : String(remito.declaredValue), observaciones: typeof remito.metadata?.observaciones === "string" ? remito.metadata.observaciones : "", destinatarioSnapshot: remito.destinatarioSnapshot, shippingAddressSnapshot: remito.shippingAddressSnapshot, transportSnapshot: remito.transportSnapshot, metadata: remito.metadata, items: remito.items.length ? remito.items.map((item) => ({ itemId: item.itemId ?? undefined, sku: item.sku ?? "", description: item.description, quantity: String(item.quantity), unit: item.unit ?? "unidad", boxId: item.boxId ?? undefined, presupuestoItemId: item.presupuestoItemId ?? undefined, lotNumber: item.lotNumber ?? "", serialNumber: item.serialNumber ?? "", expirationDate: item.expirationDate?.slice(0, 10) ?? "", metadata: item.metadata ?? undefined })) : [emptyItem()] }
}
const optional = (value: string) => value.trim() || undefined
const nullable = (value: string) => optional(value) ?? null
function merged(snapshot: Record<string, unknown> | null, values: Record<string, string | undefined>) { const result = { ...(snapshot ?? {}) }; Object.entries(values).forEach(([key, value]) => value === undefined ? delete result[key] : result[key] = value); return Object.keys(result).length ? result : null }
function payloadFor(draft: Draft): CreateRemitoPayload {
  const domicilio = optional(draft.domicilio), localidad = optional(draft.localidad), provincia = optional(draft.provincia)
  return { branchId: optional(draft.branchId) ?? "", issuedBranchId: optional(draft.issuedBranchId) ?? optional(draft.branchId), surgeryId: optional(draft.surgeryId), origin: draft.origin, salidaReason: draft.salidaReason, boxId: nullable(draft.boxId), presupuestoId: nullable(draft.presupuestoId), destinatarioContactId: nullable(draft.destinatarioContactId), destinatarioSnapshot: merged(draft.destinatarioSnapshot, { nombre: optional(draft.destinatarioNombre), domicilio, localidad, provincia }), shippingAddressSnapshot: merged(draft.shippingAddressSnapshot, { domicilio, localidad, provincia }), transportSnapshot: merged(draft.transportSnapshot, { nombre: optional(draft.transporte) }), packageCount: optional(draft.packageCount) ? Number(draft.packageCount) : null, declaredValue: optional(draft.declaredValue) ?? null, metadata: merged(draft.metadata, { observaciones: optional(draft.observaciones) }), items: draft.items.map((item) => ({ ...(optional(item.itemId ?? "") ? { itemId: optional(item.itemId ?? "") } : {}), sku: optional(item.sku), description: item.description.trim(), quantity: item.quantity, unit: optional(item.unit), ...(optional(item.boxId ?? "") ? { boxId: optional(item.boxId ?? "") } : {}), ...(optional(item.presupuestoItemId ?? "") ? { presupuestoItemId: optional(item.presupuestoItemId ?? "") } : {}), lotNumber: optional(item.lotNumber), serialNumber: optional(item.serialNumber), expirationDate: optional(item.expirationDate), ...(item.metadata ? { metadata: item.metadata } : {}) })) }
}
function validate(draft: Draft) { const errors: Errors = {}; if (!draft.branchId.trim()) errors.branchId = "Indicá la sucursal de salida."; if (!draft.salidaReason) errors.salidaReason = "Seleccioná el motivo de salida."; draft.items.forEach((item, index) => { if (!item.description.trim()) errors[`item-${index}-description`] = "La descripción es obligatoria."; if (!Number.isFinite(Number(item.quantity)) || Number(item.quantity) <= 0) errors[`item-${index}-quantity`] = "La cantidad debe ser mayor que cero." }); return errors }
const fieldClass = "h-10 bg-background text-sm focus-visible:ring-2 focus-visible:ring-ring"
const selectClass = "h-10 w-full rounded-md border bg-background px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:bg-muted"

export function OperationalRemitoWorkspace({ remitoId }: { remitoId?: string }) {
  const { activeCompany, currentUser } = useAuth()
  const workspaceIdentity = [currentUser?.id ?? "anonymous", activeCompany?.id ?? "no-company", remitoId ? "edit" : "create", remitoId ?? "new"].map(encodeURIComponent).join(":")

  // A complete identity key makes React unmount the prior session before any new
  // user, company, mode, or document can render with its local state or timers.
  return <OperationalRemitoWorkspaceSession key={workspaceIdentity} remitoId={remitoId} />
}

function OperationalRemitoWorkspaceSession({ remitoId }: { remitoId?: string }) {
  const router = useRouter(); const { activeCompany, currentUser, currentUserLoading, isLoading } = useAuth(); const companyId = activeCompany?.id
  const editing = Boolean(remitoId); const [draft, setDraft] = useState<Draft>(emptyDraft); const [baseline, setBaseline] = useState<Draft | null>(null); const [loaded, setLoaded] = useState<RemitoApiRow | null>(null); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [errors, setErrors] = useState<Errors>({}); const [conflict, setConflict] = useState(false); const [leaveOpen, setLeaveOpen] = useState(false); const [pendingLeave, setPendingLeave] = useState<(() => void) | null>(null); const [preset, setPreset] = useState<RemitoDevPreset | null>(null)
  const [recoveryReady, setRecoveryReady] = useState(false); const [recoveryCandidate, setRecoveryCandidate] = useState<{ draft: RecoveryDraft; staleBase: boolean } | null>(null); const [recoveryWarning, setRecoveryWarning] = useState(""); const recoveryWarned = useRef(false)
  const recoverButtonRef = useRef<HTMLButtonElement | null>(null); const continueEditingRef = useRef<HTMLButtonElement | null>(null); const recoveryOpenerRef = useRef<HTMLElement | null>(null); const leaveOpenerRef = useRef<HTMLElement | null>(null); const branchIdEditedRef = useRef(false); const presetDefaultAttemptedRef = useRef(false)
  const workspaceHeadingRef = useRef<HTMLHeadingElement | null>(null); const instanceGenerationRef = useRef(0)
  const refs = useRef<Record<string, HTMLElement | null>>({}); const dirty = JSON.stringify(draft) !== JSON.stringify(baseline ?? emptyDraft()); const locked = Boolean(loaded && loaded.state !== "Borrador")
  const recoveryContext: RemitoWorkspaceDraftContext | null = currentUser?.id && companyId ? { userId: currentUser.id, companyId, mode: editing ? "edit" : "create", ...(editing ? { remitoId } : {}) } : null
  const warnRecoveryOnce = () => { if (!recoveryWarned.current) { recoveryWarned.current = true; setRecoveryWarning("No se pudo conservar una copia temporal de estos cambios.") } }
  const clearRecovery = () => { if (recoveryContext && !clearRemitoWorkspaceDraft(recoveryContext)) warnRecoveryOnce() }
  const isCurrentInstance = (generation: number) => instanceGenerationRef.current === generation
  const lineCount = draft.items.length; const quantityTotal = useMemo(() => draft.items.reduce((total, item) => total + (Number.isFinite(Number(item.quantity)) ? Number(item.quantity) : 0), 0), [draft.items])
  useEffect(() => () => { instanceGenerationRef.current += 1 }, [])
  useEffect(() => { if (!companyId || !remitoId) return; const generation = instanceGenerationRef.current; let cancelled = false; setLoading(true); setError(""); void fetchRemito(companyId, remitoId).then((row) => { if (cancelled || !isCurrentInstance(generation)) return; const next = fromRemito(row); setLoaded(row); setDraft(next); setBaseline(next) }).catch((cause) => { if (!cancelled && isCurrentInstance(generation)) setError(cause instanceof Error ? cause.message : "No se pudo cargar el remito.") }).finally(() => { if (!cancelled && isCurrentInstance(generation)) setLoading(false) }); return () => { cancelled = true } }, [companyId, remitoId])
  useEffect(() => { if (!companyId || editing) return; const generation = instanceGenerationRef.current; let cancelled = false; void fetchRemitoDevPreset(companyId).then((next) => { if (!cancelled && isCurrentInstance(generation)) setPreset(next) }).catch(() => { if (!cancelled && isCurrentInstance(generation)) setPreset({ available: false }) }); return () => { cancelled = true } }, [companyId, editing])
  useEffect(() => {
    if (editing || !recoveryReady || recoveryCandidate || !preset?.available || presetDefaultAttemptedRef.current || branchIdEditedRef.current) return
    presetDefaultAttemptedRef.current = true
    setDraft((current) => current.branchId.trim() ? current : { ...current, branchId: preset.branch.id, issuedBranchId: current.issuedBranchId.trim() ? current.issuedBranchId : preset.branch.id })
  }, [editing, preset, recoveryCandidate, recoveryReady])
  useEffect(() => {
    setRecoveryReady(false); setRecoveryCandidate(null)
    if (!recoveryContext || isLoading || currentUserLoading || (editing && (!loaded || loading))) return
    if (locked) { clearRecovery(); setRecoveryReady(true); return }
    const stored = readRemitoWorkspaceDraft(recoveryContext, isRecoveryDraft)
    if (stored.status === "valid") { recoveryOpenerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setRecoveryCandidate({ draft: stored.envelope.draft, staleBase: editing && stored.envelope.serverBase !== loaded?.updatedAt }) }
    else if (stored.status === "invalid") clearRecovery()
    setRecoveryReady(true)
  // The server record must load before an edit draft can be assessed.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recoveryContext?.userId, recoveryContext?.companyId, recoveryContext?.mode, recoveryContext?.remitoId, isLoading, currentUserLoading, editing, loaded, loading, locked])
  useEffect(() => {
    if (!recoveryReady || !recoveryContext || !dirty || loading || saving || locked) return
    const generation = instanceGenerationRef.current
    const timeout = window.setTimeout(() => {
      if (!isCurrentInstance(generation)) return
      const result = writeRemitoWorkspaceDraft(recoveryContext, recoveryDraft(draft), loaded?.updatedAt ?? null)
      if (result.status !== "written" && isCurrentInstance(generation)) warnRecoveryOnce()
    }, 750)
    return () => window.clearTimeout(timeout)
  }, [draft, dirty, loaded?.updatedAt, loading, locked, recoveryContext, recoveryReady, saving])
  useEffect(() => { const onBeforeUnload = (event: BeforeUnloadEvent) => { if (dirty && !saving) { event.preventDefault(); event.returnValue = "" } }; window.addEventListener("beforeunload", onBeforeUnload); return () => window.removeEventListener("beforeunload", onBeforeUnload) }, [dirty, saving])
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => { if (key === "branchId") branchIdEditedRef.current = true; setDraft((current) => ({ ...current, [key]: value })); setErrors((current) => { const { [key]: _, ...rest } = current; return rest }); setError("") }
  const updateItem = (index: number, key: keyof DraftItem, value: string) => { setDraft((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) })); setErrors((current) => { const { [`item-${index}-${key}`]: _, ...rest } = current; return rest }) }
  const requestLeave = (action: () => void, opener?: HTMLElement) => { if (saving) return; if (!dirty) return action(); leaveOpenerRef.current = opener ?? (document.activeElement instanceof HTMLElement ? document.activeElement : null); setPendingLeave(() => action); setLeaveOpen(true) }
  const save = async () => { const nextErrors = validate(draft); if (Object.keys(nextErrors).length) { const generation = instanceGenerationRef.current; setErrors(nextErrors); requestAnimationFrame(() => { if (isCurrentInstance(generation)) refs.current[Object.keys(nextErrors)[0]]?.focus() }); return false } if (!companyId) { setError("No hay empresa activa."); return false }; const generation = instanceGenerationRef.current; setSaving(true); setError(""); setConflict(false); try { const createPayload = payloadFor(draft); const result = editing && loaded ? await updateRemitoDraft(companyId, loaded.id, { ...(() => { const { origin: _origin, ...patch } = createPayload; return patch })(), expectedUpdatedAt: loaded.updatedAt } as UpdateRemitoDraftPayload) : await createRemito(companyId, createPayload); if (!isCurrentInstance(generation)) return false; const next = fromRemito(result); setLoaded(result); setDraft(next); setBaseline(next); clearRecovery(); toast.success("Borrador guardado"); if (!editing) router.replace(`/remitos/${result.id}/editar`); return true } catch (cause) { if (!isCurrentInstance(generation)) return false; const isConflict = cause instanceof ApiClientError && cause.status === 409 && cause.code === "remito_update_conflict"; setConflict(isConflict); setError(isConflict ? "Otro usuario actualizó este borrador. Tus cambios locales se conservaron." : cause instanceof Error ? cause.message : "No se pudo guardar el borrador."); return false } finally { if (isCurrentInstance(generation)) setSaving(false) } }
  const emit = async () => { if (!loaded || dirty || locked || !companyId) return; const generation = instanceGenerationRef.current; setSaving(true); try { await emitirRemito(companyId, loaded.id); if (!isCurrentInstance(generation)) return; clearRecovery(); toast.success(`Remito emitido`); router.replace("/remitos") } catch (cause) { if (!isCurrentInstance(generation)) return; setError(cause instanceof Error ? cause.message : "No se pudo emitir el remito.") } finally { if (isCurrentInstance(generation)) setSaving(false) } }
  const reload = async () => { if (!companyId || !remitoId) return; if (dirty && !window.confirm("Se descartarán los cambios locales. ¿Continuar?")) return; const generation = instanceGenerationRef.current; setLoading(true); try { const row = await fetchRemito(companyId, remitoId); if (!isCurrentInstance(generation)) return; const next = fromRemito(row); setLoaded(row); setDraft(next); setBaseline(next); clearRecovery(); setConflict(false); setError("") } finally { if (isCurrentInstance(generation)) setLoading(false) } }
  const applyPreset = () => { if (!preset?.available || dirty && !window.confirm("Este ejemplo reemplazará los cambios sin guardar. ¿Continuar?")) return; const example = preset.example; setDraft({ ...emptyDraft(), branchId: preset.branch.id, issuedBranchId: preset.branch.id, surgeryId: example.surgeryId, origin: example.origin, salidaReason: example.salidaReason, destinatarioNombre: example.recipientSnapshot.nombre ?? "", destinatarioSnapshot: example.recipientSnapshot, shippingAddressSnapshot: example.shippingAddressSnapshot, transportSnapshot: example.transportSnapshot, packageCount: example.packageCount == null ? "" : String(example.packageCount), declaredValue: example.declaredValue == null ? "" : String(example.declaredValue), metadata: example.metadata, items: example.items.map((item) => ({ ...emptyItem(), ...item, quantity: String(item.quantity) })) }) }
  if (loading || isLoading || currentUserLoading) return <WorkspaceSkeleton />
  if (error && !loaded && editing) return <LockedState message={error} />
  if (locked) return <LockedState message={`Este remito está ${loaded?.state}. Los documentos emitidos no se editan.`} />
  return <div className="min-h-full bg-background pb-28"><main className="mx-auto max-w-[1600px] px-4 py-4 sm:px-6" aria-busy={saving}>
    <header className="sticky top-0 z-20 -mx-4 border-b bg-background/95 px-4 py-3 backdrop-blur-sm sm:-mx-6 sm:px-6"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-1"><Button type="button" variant="ghost" size="sm" className="min-h-11" onClick={(event) => requestLeave(() => router.push("/remitos"), event.currentTarget)}><ArrowLeft className="size-4" /> Remitos</Button>{loaded && <Button asChild type="button" variant="ghost" size="sm" className="min-h-11"><a href={`/remitos/${loaded.id}/editar`} target="_blank" rel="noopener noreferrer" aria-describedby="new-tab-concurrency-note"><ExternalLink className="size-4" /> Abrir en nueva pestaña</a></Button>}</div><div className="min-w-0 text-right"><div className="flex items-center justify-end gap-2"><h1 ref={workspaceHeadingRef} tabIndex={-1} className="truncate text-lg font-semibold">{loaded ? `Remito ${loaded.visibleNumber ? `R-${String(loaded.visibleNumber).padStart(4, "0")}` : ""}` : "Nuevo remito"}</h1>{loaded && <Badge variant="secondary">Borrador</Badge>}</div><p className="text-xs text-muted-foreground" aria-live="polite">{saving ? "Guardando…" : dirty ? "Cambios sin guardar" : loaded ? "Borrador guardado" : "Aún no guardado"}</p>{loaded && <p id="new-tab-concurrency-note" className="sr-only">La edición simultánea se verifica al guardar.</p>}</div></div></header>
    <div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem] xl:items-start"><div className="min-w-0 space-y-6"><section aria-labelledby="context-title" className="border-b pb-6"><SectionTitle id="context-title" title="Contexto de salida" description="Datos del documento y referencias operativas." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Sucursal de salida" required error={errors.branchId}><Input ref={(el) => { refs.current.branchId = el }} value={draft.branchId} onChange={(e) => update("branchId", e.target.value)} className={fieldClass} aria-invalid={Boolean(errors.branchId)} placeholder="Sucursal" /></Field><Field label="Sucursal emisora"><Input value={draft.issuedBranchId} onChange={(e) => update("issuedBranchId", e.target.value)} className={fieldClass} placeholder="Usa sucursal de salida" /></Field><Field label="Motivo de salida" required error={errors.salidaReason}><select value={draft.salidaReason} onChange={(e) => update("salidaReason", e.target.value as RemitoSalidaReason)} className={selectClass}>{REMITO_SALIDA_REASONS.map((reason) => <option key={reason} value={reason}>{{ cirugia: "Cirugía", venta: "Venta", prestamo: "Préstamo", traslado: "Traslado", ajuste: "Ajuste", otro: "Otro" }[reason]}</option>)}</select></Field><Field label="Origen"><select value={draft.origin} disabled={editing} onChange={(e) => update("origin", e.target.value as RemitoOrigin)} className={selectClass}>{REMITO_ORIGINS.map((origin) => <option key={origin} value={origin}>{{ box: "Desde caja", presupuesto: "Desde presupuesto", manual: "Carga manual", mixto: "Origen mixto" }[origin]}</option>)}</select></Field><Field label="Cirugía / expediente"><Input value={draft.surgeryId} onChange={(e) => update("surgeryId", e.target.value)} className={fieldClass} placeholder="Referencia opcional" /></Field><Field label="Destinatario"><Input value={draft.destinatarioNombre} onChange={(e) => update("destinatarioNombre", e.target.value)} className={fieldClass} placeholder="Nombre opcional" /></Field><Field label="Contacto"><Input value={draft.destinatarioContactId} onChange={(e) => update("destinatarioContactId", e.target.value)} className={fieldClass} placeholder="Referencia opcional" /></Field><Field label="Caja / depósito"><Input value={draft.boxId} onChange={(e) => update("boxId", e.target.value)} className={fieldClass} placeholder="Referencia opcional" /></Field><Field label="Presupuesto"><Input value={draft.presupuestoId} onChange={(e) => update("presupuestoId", e.target.value)} className={fieldClass} placeholder="Referencia opcional" /></Field></div>{!editing && preset?.available && <div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-4 text-xs text-muted-foreground"><span>DEV · ejemplo no persistido</span><Button type="button" size="sm" variant="outline" onClick={applyPreset}>Cargar ejemplo DEV</Button><span>Carga {preset.branch.label}; no guarda datos.</span></div>}</section>
    <section aria-labelledby="items-title" className="border-b pb-6"><div className="flex flex-wrap items-start justify-between gap-3"><SectionTitle id="items-title" title="Material remitido" description="Descripción y cantidad positiva son obligatorias. La trazabilidad se conserva en cada renglón." /><div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" disabled title="No hay catálogo disponible">Buscar producto · Próximamente</Button><Button type="button" size="sm" variant="outline" disabled title="No hay contrato de importación disponible">Importar desde… · Próximamente</Button><Button type="button" size="sm" onClick={() => { setDraft((current) => ({ ...current, items: [...current.items, emptyItem()] })); requestAnimationFrame(() => refs.current[`item-${draft.items.length}-description`]?.focus()) }}><Plus className="size-4" /> Agregar renglón</Button></div></div><p className="mt-3 text-xs text-muted-foreground">Las acciones de búsqueda e importación no están disponibles todavía; no agregan datos ni cambian el documento.</p><div className="mt-4 hidden overflow-x-auto border md:block"><table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-muted text-xs text-muted-foreground"><tr>{["SKU", "Descripción *", "Cantidad *", "Unidad", "Lote", "Serie / GTIN", "Vencimiento", ""].map((label) => <th key={label} className="border-b px-2 py-2 text-left font-medium">{label}</th>)}</tr></thead><tbody>{draft.items.map((item, index) => <ItemCells key={index} item={item} index={index} errors={errors} refs={refs} onChange={updateItem} onRemove={() => setDraft((current) => ({ ...current, items: current.items.length === 1 ? current.items : current.items.filter((_, row) => row !== index) }))} removable={draft.items.length > 1} />)}</tbody></table></div><div className="mt-4 space-y-3 md:hidden">{draft.items.map((item, index) => <MobileItem key={index} item={item} index={index} errors={errors} refs={refs} onChange={updateItem} onRemove={() => setDraft((current) => ({ ...current, items: current.items.length === 1 ? current.items : current.items.filter((_, row) => row !== index) }))} removable={draft.items.length > 1} />)}</div></section>
    <details className="border-b pb-6" open={Boolean(draft.transporte || draft.domicilio || draft.localidad || draft.provincia || draft.observaciones)}><summary className="cursor-pointer py-2 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Detalle operativo opcional</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Transporte"><Input value={draft.transporte} onChange={(e) => update("transporte", e.target.value)} className={fieldClass} /></Field><Field label="Bultos"><Input type="number" min="0" value={draft.packageCount} onChange={(e) => update("packageCount", e.target.value)} className={fieldClass} /></Field><Field label="Valor declarado"><Input type="number" min="0" step="0.01" value={draft.declaredValue} onChange={(e) => update("declaredValue", e.target.value)} className={fieldClass} /></Field><Field label="Domicilio"><Input value={draft.domicilio} onChange={(e) => update("domicilio", e.target.value)} className={fieldClass} /></Field><Field label="Localidad"><Input value={draft.localidad} onChange={(e) => update("localidad", e.target.value)} className={fieldClass} /></Field><Field label="Provincia"><Input value={draft.provincia} onChange={(e) => update("provincia", e.target.value)} className={fieldClass} /></Field><Field label="Observaciones" className="sm:col-span-2"><Textarea value={draft.observaciones} onChange={(e) => update("observaciones", e.target.value)} className="min-h-24" /></Field></div></details></div>
    <aside className="border bg-card p-4 xl:sticky xl:top-24"><h2 className="text-sm font-semibold">Resumen operativo</h2><dl className="mt-4 grid gap-3 text-sm"><Summary label="Estado" value={loaded ? "Borrador" : "Aún no guardado"} /><Summary label="Sucursal" value={draft.branchId || "Falta indicar"} alert={!draft.branchId} /><Summary label="Motivo" value={draft.salidaReason} /><Summary label="Destinatario" value={draft.destinatarioNombre || "Sin destinatario"} /><Summary label="Cirugía" value={draft.surgeryId || "Sin referencia"} /><Summary label="Renglones" value={String(lineCount)} /><Summary label="Cantidad total" value={new Intl.NumberFormat("es-AR", { maximumFractionDigits: 4 }).format(quantityTotal)} /></dl></aside></div></main>
     <footer className="fixed inset-x-0 bottom-0 z-30 border-t bg-background px-4 py-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]"><div className="mx-auto flex max-w-[1600px] flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="min-h-5 text-xs" aria-live="polite">{error && <span className="flex items-center gap-1 text-destructive"><CircleAlert className="size-3.5" /> {error}</span>}{conflict && <span className="ml-2"><Button type="button" variant="link" className="h-auto p-0 text-xs" onClick={() => void reload()}>Actualizar desde servidor</Button></span>}{!error && (saving ? <span className="flex items-center gap-1 text-muted-foreground"><Loader2 className="size-3.5 animate-spin motion-reduce:animate-none" /> Guardando…</span> : recoveryWarning || (dirty ? "Cambios sin guardar" : ""))}</div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={(event) => requestLeave(() => router.push("/remitos"), event.currentTarget)} disabled={saving}>Volver</Button><Button type="button" variant="outline" onClick={() => void save()} disabled={saving}>{saving ? "Guardando…" : editing ? "Guardar cambios" : "Guardar borrador"}</Button>{editing && <Button type="button" onClick={() => void emit()} disabled={saving || dirty}><Send className="size-4" /> Emitir</Button>}</div></div></footer>
      <Dialog open={Boolean(recoveryCandidate)} onOpenChange={(open) => { if (!open) setRecoveryCandidate(null) }}>
        <DialogContent showCloseButton={false} className="sm:max-w-md" onOpenAutoFocus={(event) => { event.preventDefault(); (recoverButtonRef.current?.isConnected ? recoverButtonRef.current : workspaceHeadingRef.current)?.focus() }} onCloseAutoFocus={(event) => { event.preventDefault(); (recoveryOpenerRef.current?.isConnected ? recoveryOpenerRef.current : workspaceHeadingRef.current)?.focus() }}>
          <DialogHeader><DialogTitle>Recuperar cambios sin guardar</DialogTitle><DialogDescription>Encontramos una copia temporal de este remito en esta sesión.</DialogDescription></DialogHeader>
          {recoveryCandidate?.staleBase && <p role="status" className="text-sm text-amber-700">El remito fue actualizado en el servidor desde esta copia. Al guardar se conservará el control de concurrencia.</p>}
          <DialogFooter><Button variant="outline" onClick={() => { clearRecovery(); setRecoveryCandidate(null) }}>Descartar</Button><Button ref={recoverButtonRef} onClick={() => { if (!recoveryCandidate) return; setDraft({ ...emptyDraft(), ...recoveryCandidate.draft, items: recoveryCandidate.draft.items.map((item) => ({ ...emptyItem(), ...item })) }); setRecoveryCandidate(null) }}>Recuperar</Button></DialogFooter>
        </DialogContent>
      </Dialog>
      <Dialog open={leaveOpen} onOpenChange={(open) => { setLeaveOpen(open); if (!open) setPendingLeave(null) }}>
        <DialogContent showCloseButton={false} className="sm:max-w-md" onOpenAutoFocus={(event) => { event.preventDefault(); continueEditingRef.current?.focus() }} onCloseAutoFocus={(event) => { event.preventDefault(); leaveOpenerRef.current?.focus() }}>
          <DialogHeader><DialogTitle>Cambios sin guardar</DialogTitle><DialogDescription>Podés guardarlos antes de salir o descartarlos.</DialogDescription></DialogHeader>
          <DialogFooter><Button ref={continueEditingRef} variant="outline" onClick={() => setLeaveOpen(false)}>Seguir editando</Button><Button variant="outline" onClick={() => { clearRecovery(); setLeaveOpen(false); pendingLeave?.() }}>Descartar cambios</Button><Button onClick={() => void save().then((saved) => { if (saved) { setLeaveOpen(false); pendingLeave?.() } })}>Guardar borrador</Button></DialogFooter>
        </DialogContent>
      </Dialog>
  </div>
}

function SectionTitle({ id, title, description }: { id: string; title: string; description: string }) { return <div><h2 id={id} className="text-base font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div> }
function Field({ label, required, error, className, children }: { label: string; required?: boolean; error?: string; className?: string; children: React.ReactNode }) { const id = useId(); const errorId = `${id}-error`; const control = React.isValidElement<{ id?: string; "aria-describedby"?: string }>(children) ? React.cloneElement(children, { id: children.props.id ?? id, "aria-describedby": error ? errorId : children.props["aria-describedby"] }) : children; return <div className={`grid gap-1.5 ${className ?? ""}`}><Label htmlFor={id} className="text-xs font-medium">{label}{required ? " *" : ""}</Label>{control}{error && <p id={errorId} className="text-xs text-destructive" role="alert">{error}</p>}</div> }
function Summary({ label, value, alert }: { label: string; value: string; alert?: boolean }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className={alert ? "mt-0.5 font-medium text-destructive" : "mt-0.5 break-words"}>{value}</dd></div> }
function ItemCells({ item, index, errors, refs, onChange, onRemove, removable }: { item: DraftItem; index: number; errors: Errors; refs: React.MutableRefObject<Record<string, HTMLElement | null>>; onChange: (index: number, key: keyof DraftItem, value: string) => void; onRemove: () => void; removable: boolean }) { const input = (key: keyof DraftItem, label: string, type = "text") => <Input ref={key === "description" || key === "quantity" ? (el) => { refs.current[`item-${index}-${key}`] = el } : undefined} type={type} min={key === "quantity" ? "0.0001" : undefined} step={key === "quantity" ? "0.0001" : undefined} value={item[key] as string} onChange={(e) => onChange(index, key, e.target.value)} className={`${fieldClass} ${key === "quantity" ? "text-right tabular-nums" : ""}`} aria-label={`${label} del renglón ${index + 1}`} aria-invalid={Boolean(errors[`item-${index}-${key}`])} />; return <tr><td className="border-b p-1">{input("sku", "SKU")}</td><td className="border-b p-1">{input("description", "Descripción")}{errors[`item-${index}-description`] && <p className="text-xs text-destructive">{errors[`item-${index}-description`]}</p>}</td><td className="border-b p-1">{input("quantity", "Cantidad", "number")}{errors[`item-${index}-quantity`] && <p className="text-xs text-destructive">{errors[`item-${index}-quantity`]}</p>}</td><td className="border-b p-1">{input("unit", "Unidad")}</td><td className="border-b p-1">{input("lotNumber", "Lote")}</td><td className="border-b p-1">{input("serialNumber", "Serie o GTIN")}</td><td className="border-b p-1">{input("expirationDate", "Vencimiento", "date")}</td><td className="border-b p-1"><Button type="button" variant="ghost" size="icon" disabled={!removable} aria-label={`Quitar renglón ${index + 1}`} onClick={onRemove}><Trash2 className="size-4" /></Button></td></tr> }
function MobileItem(props: Parameters<typeof ItemCells>[0]) { const { item, index, errors, refs, onChange, onRemove, removable } = props; const control = (key: keyof DraftItem, label: string, type = "text") => <Field label={label} error={errors[`item-${index}-${key}`]}><Input ref={key === "description" || key === "quantity" ? (el) => { refs.current[`item-${index}-${key}`] = el } : undefined} type={type} min={key === "quantity" ? "0.0001" : undefined} step={key === "quantity" ? "0.0001" : undefined} value={item[key] as string} onChange={(e) => onChange(index, key, e.target.value)} className={fieldClass} aria-label={`${label} del renglón ${index + 1}`} /></Field>; return <fieldset className="border p-3"><legend className="px-1 text-xs font-medium text-muted-foreground">Renglón {index + 1}</legend><div className="grid gap-3">{control("description", "Descripción *")}{control("quantity", "Cantidad *", "number")}<div className="grid grid-cols-2 gap-3">{control("sku", "SKU")}{control("unit", "Unidad")}{control("lotNumber", "Lote")}{control("serialNumber", "Serie / GTIN")}</div>{control("expirationDate", "Vencimiento", "date")}<Button type="button" variant="outline" disabled={!removable} onClick={onRemove}><Trash2 className="size-4" /> Quitar renglón</Button></div></fieldset> }
function WorkspaceSkeleton() { return <div className="min-h-full bg-background p-6"><div className="mx-auto max-w-[1600px] animate-pulse motion-reduce:animate-none"><div className="h-14 border-b bg-muted/40" /><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_20rem]"><div className="space-y-6"><div className="h-52 bg-muted/40" /><div className="h-80 bg-muted/40" /></div><div className="h-72 bg-muted/40" /></div></div></div> }
function LockedState({ message }: { message: string }) { const router = useRouter(); return <main className="mx-auto max-w-xl p-6"><div className="border bg-card p-6"><FilePlus2 className="size-5 text-muted-foreground" /><h1 className="mt-4 text-lg font-semibold">Edición no disponible</h1><p className="mt-2 text-sm text-muted-foreground">{message}</p><Button className="mt-5" onClick={() => router.replace("/remitos")}>Volver a remitos</Button></div></main> }
