"""Generate documents 02-04."""
import json
from pathlib import Path

OUT_DIR = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\docs\migration-consultar-plus\minimax-audit")
TMP = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\.tmp\consultar-plus-minimax-audit")


def load(name):
    with open(TMP / name, encoding="utf-8") as f:
        return json.load(f)


inv = load("00_inventory.json")
profiles = load("02_core_profiles.json")
big = load("03_big_tables_header.json")
cir2026 = load("04_cirugias_2026.json")

# Compute top tables summary
ok = [x for x in inv if not x.get("error")]
sorted_by_records = sorted(ok, key=lambda x: -x["header"]["numrecords"])

doc02_lines = []
doc02_lines.append("# 02 — Inventario Independiente del Backup Legacy")
doc02_lines.append("")
doc02_lines.append("**Origen:** `E:\\OSSUM_COR_ANTIGRAVITY\\Backup_DistriCorr_29092026`")
doc02_lines.append("**Método:** Header-only (32 bytes por DBF) + iteración completa para CIRCOD/STOCK1 sample.")
doc02_lines.append("**Encoding por defecto:** `cp1252` (Windows Latin-1).")
doc02_lines.append("**Total archivos DBF:** 510")
doc02_lines.append("**Total registros (suma):** " + f"{sum(x['header']['numrecords'] for x in ok):,}")
doc02_lines.append("**Con memo (.FPT):** " + str(sum(1 for x in ok if x['has_memo'])))
doc02_lines.append("**Con índice (.CDX):** " + str(sum(1 for x in ok if x['has_cdx'])))
doc02_lines.append("**Con deleted records:** " + str(sum(1 for x in ok if (x.get('deleted_records') or 0) > 0)))
doc02_lines.append("")
doc02_lines.append("## Top 30 tablas por volumen")
doc02_lines.append("")
doc02_lines.append("| # | Tabla | Registros | Deleted | Bytes | Campos | Memo | CDX |")
doc02_lines.append("|---|-------|----------:|--------:|------:|-------:|:----:|:---:|")
for i, x in enumerate(sorted_by_records[:30], 1):
    h = x["header"]
    doc02_lines.append(f"| {i} | `{x['name_upper']}` | {h['numrecords']:,} | {x.get('deleted_records', 0) or 0} | {x['size_bytes']:,} | {x['num_fields']} | {'Y' if x['has_memo'] else 'N'} | {'Y' if x['has_cdx'] else 'N'} |")
doc02_lines.append("")
doc02_lines.append("## Tablas quirúrgicas núcleo")
doc02_lines.append("")
doc02_lines.append("| Tabla | Registros | Campos | Encoding | Memo |")
doc02_lines.append("|-------|----------:|-------:|----------|:---:|")
core = ["CIRUGIA", "CIRNOTAS", "CIRTIP", "CLIENTE", "ARTICULO", "STOCK", "STOCK1", "STOCKH", "CUENTAS", "CUENTASD", "CUENTASH", "HISCAM", "HISCOS", "HISREG", "HISCON", "HISPRE", "VARHIS", "FORMHIS", "FORMULA1", "CLIATRI", "ARTATRI", "ATRIENT"]
for n in core:
    matches = [x for x in ok if x['name_upper'].upper() == f"{n}.DBF"]
    for x in matches:
        h = x["header"]
        doc02_lines.append(f"| `{x['name_upper']}` | {h['numrecords']:,} | {x['num_fields']} | {x['encoding']} | {'Y' if x['has_memo'] else 'N'} |")
doc02_lines.append("")
doc02_lines.append("## Catálogos pequeños (referencia)")
doc02_lines.append("")
doc02_lines.append("| Tabla | Registros | Descripción inferida |")
doc02_lines.append("|-------|----------:|---------------------|")
catalogs = {
    "VIAJANTE": 7, "OBRAS": 11, "MEDPAG": 26, "CONDPAG": 8,
    "CENCOS": 5, "CONCEPTO": 6, "CONCEP": 87, "SUCURSALES": 2,
    "EMPRESA": 2, "LOCALIDA": 1236, "PROVINCI": 25, "TRANSPOR": 68,
    "BANCOS": 188, "ADMGRP": 8, "ADMGRP1": 39, "ADMUSR": 27,
    "CIRTIP": 75, "NUMERATO": 104, "OBSASO": 18074,
}
for n, exp in catalogs.items():
    matches = [x for x in ok if x['name_upper'].upper() == f"{n}.DBF"]
    if matches:
        actual = matches[0]['header']['numrecords']
        doc02_lines.append(f"| `{matches[0]['name_upper']}` | {actual:,} | - |")
    else:
        doc02_lines.append(f"| `{n}.DBF` | NO ENCONTRADO | - |")
doc02_lines.append("")
doc02_lines.append("## Observaciones")
doc02_lines.append("")
doc02_lines.append("- **Deleted records** detectados (mayoritarios): `cambio.dbf` (150), `Precioarbak.dbf` (77), `formolis.dbf` (4 — archivo huérfano), `FORMULA2.DBF` (46). En general pocos deleted flags.")
doc02_lines.append("- **Encoding cp1252**: las tildes/ñ no se pierden, pero caracteres de imprenta rara (0x81, 0x9d) fuerzan `errors='replace'` en algunos archivos. La estructura no se ve afectada.")
doc02_lines.append("- **Disco**: el backup mide ~700 MB total en DBF/FPT/CDX.")
doc02_lines.append("")
doc02_lines.append("## Diferencias vs expectativas")
doc02_lines.append("")
doc02_lines.append("- Esperaba ~200-300 tablas en un ERP típico. Aquí hay 510 — sistema multi-módulo (compras, ventas, contabilidad, stock, RRHH, AFIP, etc.).")
doc02_lines.append("- El módulo quirúrgico es solo una parte menor: 7,514 cirugías vs 22,055 ventas y 312,095 movimientos de stock.")
doc02_lines.append("- Hay una tabla `formolis.dbf` huérfana (sin CDX, en raíz, modificada 2025-04-24) — probablemente backup temporal.")
doc02_lines.append("")
doc02_lines.append("## Datos derivados")
doc02_lines.append("")
doc02_lines.append(f"`{len(inv)} archivos` → `{sum(x['header']['numrecords'] for x in ok):,} registros totales`")

(OUT_DIR / "02_INVENTARIO_INDEPENDIENTE.md").write_text("\n".join(doc02_lines), encoding="utf-8")
print("Wrote 02")

# ════════════════════════════════════════════════════════════════════
# Documento 03: Modelo Legacy
# ════════════════════════════════════════════════════════════════════
doc03_lines = []
doc03_lines.append("# 03 — Modelo Legacy (Reconstrucción Independiente)")
doc03_lines.append("")
doc03_lines.append("## Método")
doc03_lines.append("")
doc03_lines.append("- Cross-reference por nombre de campo (CIRCOD en CIRUGIA → STKCIRCOD en STOCK).")
doc03_lines.append("- Cobertura: matches / huérfanos / cardinalidad.")
doc03_lines.append("- Confirmación por inspección de valores en muestra.")
doc03_lines.append("")
doc03_lines.append("## Tablas del núcleo quirúrgico")
doc03_lines.append("")
doc03_lines.append("### CIRUGIA (7,512 registros, 43 campos, memo)")
doc03_lines.append("")
doc03_lines.append("Campos clave:")
doc03_lines.append("- `CIRCOD` (N 7) — **PK** (7,512 únicos, 0 duplicados)")
doc03_lines.append("- `CIRFEC` (D 8) — fecha de la cirugía (3,106 NN = 41.4%; el resto aún no ocurrió)")
doc03_lines.append("- `CIRFECCAR` (D 8) — fecha de carga del registro (100% NN)")
doc03_lines.append("- `CIRFECLOG` (D 8) — fecha de envío/logística del material (2,868 NN = 38.2%)")
doc03_lines.append("- `CIRESTADO` (C 3) — estado actual (ver §04)")
doc03_lines.append("- `CIROBS` (M 4) — observación memo (816 NN)")
doc03_lines.append("- `CIRMEDCOD` (C 5) — **FK a CLIENTE.CLICOD** (5,900 NN; 100% match)")
doc03_lines.append("- `CIRMED` (C 60) — nombre del médico cacheado (vacío — siempre desde FK)")
doc03_lines.append("- `CIRHOSCOD` (C 5) — **FK a CLIENTE.CLICOD** (4,687 NN; 99.99% match)")
doc03_lines.append("- `CIROSCOD` (C 5) — **FK a CLIENTE.CLICOD** (7,512 NN; 100% match)")
doc03_lines.append("- `CIRPACCOD` (C 5) — **FK a CLIENTE.CLICOD** (7,360 NN; 99.99% match)")
doc03_lines.append("- `CIRPAC` (C 60) — nombre del paciente cacheado")
doc03_lines.append("- `CIRAUT` (C 1) — ¿autorizada? S/N (3,953 S / 3,559 N)")
doc03_lines.append("- `CIRAUTNRO` (C 40) — número de autorización (5,243 NN)")
doc03_lines.append("- `CIRFV` / `CIRLEYFV` — foto verificación / ley")
doc03_lines.append("- `CIRPRCOD` / `CIRPRNRO` — código/número de presupuesto")
doc03_lines.append("- `CIRFVCOD` / `CIRNRCOD` / `CIRCOCOD` / `CIRFCCOD` — campos varios")
doc03_lines.append("- `CIRRE` — campo 5-char con pattern `NNSNN` (7,347) / `NSNNN` (163) — flags combinados")
doc03_lines.append("- `CIRDOCRE` / `CIRDOCRE` / `CIRDOCPR` / `CIRDOCRX` / `CIRAUTFV` — flags S/N de documentos (recibo/certificado/protocolo/rx/factura-verifica)")
doc03_lines.append("- `VIACOD` (C 5) — vendedor/coordinador (5,652 NN; FK a VIAJANTE.VIACOD)")
doc03_lines.append("- `AUSRID` (C 10) — usuario que carga (todos 7,512 NN; 9 usuarios distintos, BETIANA domina 66%)")
doc03_lines.append("- `CIRTIP` (C 10) — tipo de cirugía (FK a CIRTIP; 2,782 NN; 57 distintos)")
doc03_lines.append("- `CIRHORA` (N 5) — hora (7,499 = '0' = sin hora)")
doc03_lines.append("- `CIRDOC` (C 20) — flags de documentos concatenados (12 chars, pattern `S/N`*12)")
doc03_lines.append("")
doc03_lines.append("### CLIENTE (9,078 registros, 215 campos, memo)")
doc03_lines.append("")
doc03_lines.append("Tabla universal de **todo contacto**: pacientes, médicos, hospitales, obras sociales, vendedores, droguerías, clientes finales.")
doc03_lines.append("")
doc03_lines.append("Campos clave para migración:")
doc03_lines.append("- `CLICOD` (C 5) — **PK**")
doc03_lines.append("- `CLINOM` (C 60) — nombre / razón social")
doc03_lines.append("- `CLINOMFAN` (C 60) — nombre fantasía")
doc03_lines.append("- `CLIDNI` (N 8) — DNI / CUIT (no valida formato)")
doc03_lines.append("- `CLICUI` (C 13) — CUIT")
doc03_lines.append("- `CLIDOM` / `CLIDOMLAB` / `CLIDOMENV` — domicilios")
doc03_lines.append("- `CLITEL` / `CLITELLAB` — teléfonos")
doc03_lines.append("- `CLIEMA` — email")
doc03_lines.append("- `CLIRES` (C 40) — responsable")
doc03_lines.append("- `CLICPA` / `CLIPOSCOD` — códigos postales")
doc03_lines.append("- `CLIFECING` / `CLIFECNAC` — fechas ingreso / nacimiento")
doc03_lines.append("- `CLISEX` — sexo")
doc03_lines.append("- `CLICIR` (C 2) — **flag paciente** (no se observó uso claro en muestra)")
doc03_lines.append("- `CLIAFPICOD` — código AFIP")
doc03_lines.append("- `CLIAct` (C 1) — S/N activo")
doc03_lines.append("- `CLICODGES` — gestor asignado")
doc03_lines.append("- ~150 campos más contables/financieros (no relevantes para OSSUM core)")
doc03_lines.append("")
doc03_lines.append("### CIRNOTAS (6,365 registros, 6 campos, memo)")
doc03_lines.append("")
doc03_lines.append("- `CIRNOTCOD` (N 5) — PK")
doc03_lines.append("- `CIRCOD` (N 7) — **FK a CIRUGIA**")
doc03_lines.append("- `CIRNOTUSR` (C 10) — usuario que carga la nota (25 usuarios)")
doc03_lines.append("- `CIRNOTFEC` (D 8) — fecha de la nota (rango 2025-03-06 → 2026-09-29)")
doc03_lines.append("- `CIRNOTHORA` (C 8) — hora")
doc03_lines.append("- `CIRNOTA` (M 4) — texto memo (98.4% NN)")
doc03_lines.append("")
doc03_lines.append("**Hallazgo crítico:** CIRNOTAS arranca el 2025-03-06 — solo tiene 1.5 años de historia. Las cirugías pre-2025 no tienen notas.")
doc03_lines.append("")
doc03_lines.append("### CIRTIP (75 registros, 4 campos)")
doc03_lines.append("")
doc03_lines.append("Catálogo de tipos de cirugía:")
doc03_lines.append("- `CIRTIP` (C 10) — código")
doc03_lines.append("- `CIRTIPDES` (C 60) — descripción")
doc03_lines.append("- `CIRTIPACT` (C 1) — S/N activo (72 S, 3 N)")
doc03_lines.append("- `CIRTIPPRE` (N 14) — precio (45 distintos)")
doc03_lines.append("")
doc03_lines.append("### STOCK (9,754 registros, 36 campos)")
doc03_lines.append("")
doc03_lines.append("- `STKCOD` (N 8) — **PK** (movimiento header)")
doc03_lines.append("- `STKCOM` (C 2) — tipo de comprobante (NR/RE/AJ/TR/CV/FV/TV/CM/PE/LV/FC) — ver §05")
doc03_lines.append("- `STKTIP` (C 1) — tipo (A/B/C) — ver §05")
doc03_lines.append("- `STKES` (C 1) — E/S entrada/salida")
doc03_lines.append("- `STKDEV` (C 1) — S/N es devolución")
doc03_lines.append("- `STKSUC` / `STKSUCCAR` — sucursal (5 distintos)")
doc03_lines.append("- `STKNRO` (N 8) — número del comprobante")
doc03_lines.append("- `STKFEC` (D 8) — fecha del movimiento")
doc03_lines.append("- `DPSCODENT` / `DPSCODSAL` (C 5) — depósito entrada/salida")
doc03_lines.append("- `CLICOD` (C 5) — **FK a CLIENTE** (9,110 NN; 200+ distintos)")
doc03_lines.append("- `STKVTACOD` (N 8) — **FK a CUENTAS.VTACOD** (8,666 NN)")
doc03_lines.append("- `STKCIRCOD` (N 7) — **FK a CIRUGIA.CIRCOD** (5,822 NN; 200+ distintos)")
doc03_lines.append("- `STKORDPRO` (N 8) — orden de producción")
doc03_lines.append("- `STKTRACOD` (C 5) — transportista")
doc03_lines.append("- `STKOBS` / `STKCONCE` — observación/concepto")
doc03_lines.append("")
doc03_lines.append("### STOCK1 (312,095 registros, 55 campos, memo)")
doc03_lines.append("")
doc03_lines.append("Detalle del movimiento de stock.")
doc03_lines.append("")
doc03_lines.append("- `STKCOD` (N 8) — **FK a STOCK.STKCOD**")
doc03_lines.append("- `MOVORD` (N 8) — número de línea")
doc03_lines.append("- `ARTCOD` (C 13) — **FK a ARTICULO.ARTCOD**")
doc03_lines.append("- `MOVDEP` (C 5) — depósito")
doc03_lines.append("- `MOVSER` (C 13) — serie/lote")
doc03_lines.append("- `MOVCAN` (N 12,2) — cantidad")
doc03_lines.append("- `MOVFEC` (D 8) — fecha")
doc03_lines.append("- `MOVES` (C 1) — E/S")
doc03_lines.append("- `MOVUNI` (C 3) — unidad (S=stock, V=venta, C=?)")
doc03_lines.append("- `MOVCON` (N 11,4) — confirmado? (1.0 = sí)")
doc03_lines.append("- `MOVCER` (C 1) — cerrado S/N")
doc03_lines.append("- `MOVSTKCOD` / `MOVMOVORD` — referencia reversa (link a movimiento opuesto)")
doc03_lines.append("- `MOVVTACOD` (N 8) — **FK a CUENTAS.VTACOD** (1,331 NN)")
doc03_lines.append("- `MOVPEDCOD` / `MOVPEDORD` — pedido")
doc03_lines.append("- `MOVNROSER` (C 20) — número de serie")
doc03_lines.append("- `MOVGTING` / `MOVPM` — atributos del artículo (mirror de ARTATRI)")
doc03_lines.append("- `MOVNOCSIN` / `MOVNOCCAU` / `MOVNOCPRI` — campos memo de no-conformidades")
doc03_lines.append("")
doc03_lines.append("### CUENTAS (22,055 registros, 90 campos)")
doc03_lines.append("")
doc03_lines.append("Comprobantes de venta (facturación).")
doc03_lines.append("")
doc03_lines.append("- `VTACOD` (N 8) — **PK**")
doc03_lines.append("- `CPTECOD` (C 2) — tipo comprobante fiscal")
doc03_lines.append("- `VTACOM` (C 2) — clase comprobante")
doc03_lines.append("- `VTATIP` (C 1) — tipo (A=Factura A, B=Factura B, C=Factura C)")
doc03_lines.append("- `VTASUC` / `VTASUCCAR` (N 4) — sucursal (1/4/5/10)")
doc03_lines.append("- `VTANRO` (N 8) — número")
doc03_lines.append("- `CLICOD` (C 5) — **FK a CLIENTE**")
doc03_lines.append("- `VTAFECEMI` / `VTAFECCON` — fecha emisión / contable")
doc03_lines.append("- `VTAFECENT` — fecha entrega")
doc03_lines.append("- `VTATOTAL` (N 12) — total")
doc03_lines.append("- `VTAMONID` / `VTACOTMON` — moneda / cotización")
doc03_lines.append("- `VTAAUTIMP` — autorización impresión (AFIP)")
doc03_lines.append("- `VTACAI` / `VTACAIFEC` — CAE AFIP")
doc03_lines.append("- `VTACPTEV` (C 1) — tipo comprobante venta (V/C/...)")
doc03_lines.append("- `VTAIMP` (C 1) — impresa S/N")
doc03_lines.append("- `VTAELE` (C 1) — electrónica S/N")
doc03_lines.append("- `VTAESTTRA` / `VTAESTCOM` — estado transferencia/comprobante")
doc03_lines.append("- `VTACIRCOD` (N 7) — **FK a CIRUGIA.CIRCOD** (FK directa, redundancy con STOCK)")
doc03_lines.append("- `VTADOMCOD` / `VTADOMENV` — domicilio de entrega")
doc03_lines.append("- `VTATRACOD` (C 5) — transportista")
doc03_lines.append("- `REPNRO` (N 8) — número de reparto (link a REPARTO)")
doc03_lines.append("")
doc03_lines.append("### CUENTASD (56,021 registros, 62 campos)")
doc03_lines.append("")
doc03_lines.append("Líneas de detalle de factura:")
doc03_lines.append("- `VTACOD` — FK a CUENTAS")
doc03_lines.append("- `DETORD` — número de línea")
doc03_lines.append("- `ARTCOD` (C 13) — FK a ARTICULO")
doc03_lines.append("- `DETSER` (C 30) — serie/lote")
doc03_lines.append("- `DETCAN` (N 14) — cantidad")
doc03_lines.append("- `DETPREVEN` / `DETPRECOS` — precios venta/costo")
doc03_lines.append("- `DETIMPIVA` / `DETIVA` — IVA")
doc03_lines.append("- `DETDTO1/2/3` — descuentos")
doc03_lines.append("- `DETDEP` — depósito")
doc03_lines.append("- `DETSTKCOD` / `DETSTKORD` — **FK a STOCK1.STKCOD/MOVORD**")
doc03_lines.append("- `DETCTACOD` — cuenta contable")
doc03_lines.append("- `DETFEC` — fecha")
doc03_lines.append("")
doc03_lines.append("### CLIATRI (92,701 registros, 6 campos, memo)")
doc03_lines.append("")
doc03_lines.append("Atributos extensibles por cliente (EAV).")
doc03_lines.append("- `CLICOD` (C 5) — FK a CLIENTE")
doc03_lines.append("- `ATRDES` (C 50) — nombre del atributo (AFIP_GRAN_EMPRESA, FCE_MONTO_MINIMO, GLN, SUCURSAL_PROPUESTA, LOGISTICA, ALTERNATIVOS, etc.)")
doc03_lines.append("- `DATCLICAR` (C 60) — valor string")
doc03_lines.append("- `DATCLINUM` (N 12) — valor numérico")
doc03_lines.append("- `DATCLIFEC` — valor fecha")
doc03_lines.append("- `DATCLIMEM` (M 4) — valor memo")
doc03_lines.append("")
doc03_lines.append("### ARTATRI (24,190 registros, 5 campos)")
doc03_lines.append("")
doc03_lines.append("Atributos extensibles por artículo:")
doc03_lines.append("- `ARTCOD` (C 13) — FK a ARTICULO")
doc03_lines.append("- `ATRDES` (C 50) — nombre atributo (GTING, PM)")
doc03_lines.append("- `DATARTCAR` (C 200) — valor string")
doc03_lines.append("- `DATARTNUM` — valor numérico")
doc03_lines.append("- `DATARTFEC` — valor fecha")
doc03_lines.append("")
doc03_lines.append("### ATRIENT (190,270 registros, 8 campos)")
doc03_lines.append("")
doc03_lines.append("Catálogo de valores de atributos. (Schema no leído en detalle; sirve como dimensión de catálogo de atributos.)")
doc03_lines.append("")
doc03_lines.append("### FORMULA1 / FORMULA2 / FORMHIS (BOM de artículos)")
doc03_lines.append("")
doc03_lines.append("- `FORMULA1` (94,735 rec): lista de materiales (BOM) por artículo padre (`FORFABCOD`)")
doc03_lines.append("- `FORMULA2` (8,728 rec): tablas auxiliares de fórmulas")
doc03_lines.append("- `FORMHIS` (164,971 rec): histórico de fórmulas")
doc03_lines.append("")
doc03_lines.append("### HISCAM / HISCOS / HISREG / HISCON / HISPRE / HISVAL (Auditoría)")
doc03_lines.append("")
doc03_lines.append("- `HISCAM` (56,679 rec): cambios de campo por tabla (`HISCAMTAB` ∈ CIRUGIA/CUENTAS/ARTICULO/CLIENTE/VARIA/ADMUSR)")
doc03_lines.append("- `HISCOS` (9,264 rec): histórico de costos por artículo")
doc03_lines.append("- `HISREG` (60,405 rec): cambios a VTACOD/STKCOD/ASINRO (trigger-based)")
doc03_lines.append("- `HISCON` (13,808 rec): rangos numéricos usados por día")
doc03_lines.append("- `HISPRE` (6,831 rec): histórico de precios")
doc03_lines.append("- `HISVAL` (883 rec): histórico de valores (impuestos/IVA)")
doc03_lines.append("- `VARHIS` (7,578 rec): histórico de variantes")
doc03_lines.append("")
doc03_lines.append("### USER / AUTH")
doc03_lines.append("")
doc03_lines.append("- `ADMUSR` (27 rec): usuarios del sistema")
doc03_lines.append("- `ADMGRP` (8 rec): grupos")
doc03_lines.append("- `ADMGRP1` (39 rec): pertenencia grupo-usuario")
doc03_lines.append("- `ADMMAP` (8,379 rec): permission map (sistema / pgm / evento / grupo)")
doc03_lines.append("- `ADMEVN` — eventos del sistema")
doc03_lines.append("- `PREFUSR` (8,707 rec): preferencias por usuario")
doc03_lines.append("")
doc03_lines.append("## Diagrama relacional lógico")
doc03_lines.append("")
doc03_lines.append("```")
doc03_lines.append("                          ┌──────────────┐")
doc03_lines.append("                          │  CLIENTE     │  (universal)")
doc03_lines.append("                          │  (9,078)     │")
doc03_lines.append("                          └──────┬───────┘")
doc03_lines.append("           ┌──────────────────────┼──────────────────────┐")
doc03_lines.append("           │                      │                      │")
doc03_lines.append("     pac/med/hos/os         CLIATRI (92,701)        VIAJANTE (7)")
doc03_lines.append("           │                  atributos                vendedores")
doc03_lines.append("           ▼                                              │")
doc03_lines.append("    ┌─────────────┐                                     │")
doc03_lines.append("    │  CIRUGIA    │◄─── CIRNOTAS (6,365)                │")
doc03_lines.append("    │  (7,512)    │◄─── CIRTIP (75)                     │")
doc03_lines.append("    │  43 campos  │◄─── VIAJANTE                        │")
doc03_lines.append("    └──────┬──────┘                                     │")
doc03_lines.append("           │ CIRCOD                                      │")
doc03_lines.append("           ▼                                             │")
doc03_lines.append("    ┌─────────────┐                                     │")
doc03_lines.append("    │   STOCK     │                                     │")
doc03_lines.append("    │  (9,754)    │──► STKVTACOD ──┐                    │")
doc03_lines.append("    │  36 campos  │──► STKCIRCOD   │                    │")
doc03_lines.append("    └──────┬──────┘──► CLICOD ─────┤                    │")
doc03_lines.append("           │                        │                   │")
doc03_lines.append("           ▼                        ▼                   │")
doc03_lines.append("    ┌─────────────┐          ┌─────────────┐            │")
doc03_lines.append("    │   STOCK1    │          │  CUENTAS    │            │")
doc03_lines.append("    │ (312,095)   │          │ (22,055)    │            │")
doc03_lines.append("    │  55 campos  │          │  90 campos  │            │")
doc03_lines.append("    │  artcod     │          │  VTACIRCOD  │            │")
doc03_lines.append("    │  movstkcod ─┘          └──────┬──────┘            │")
doc03_lines.append("    │ (self-ref reversa)           │                   │")
doc03_lines.append("    │                              ▼                   │")
doc03_lines.append("    │                       ┌─────────────┐            │")
doc03_lines.append("    │                       │  CUENTASD   │            │")
doc03_lines.append("    │                       │ (56,021)    │            │")
doc03_lines.append("    │                       │  artcod     │            │")
doc03_lines.append("    │                       └──────┬──────┘            │")
doc03_lines.append("    │                              │                   │")
doc03_lines.append("    ▼                              ▼                   ▼")
doc03_lines.append("    ┌─────────────┐          ┌─────────────┐  ┌──────────────┐")
doc03_lines.append("    │  ARTICULO   │◄─────────│  ARTATRI    │  │  TRANSPOR    │")
doc03_lines.append("    │ (5,902)     │          │ (24,190)    │  │   (68)       │")
doc03_lines.append("    │  115 campos │          │  atributos  │  │              │")
doc03_lines.append("    └─────────────┘          └─────────────┘  └──────────────┘")
doc03_lines.append("```")
doc03_lines.append("")
doc03_lines.append("## Cardinalidades clave verificadas")
doc03_lines.append("")
doc03_lines.append("| Relación | Padre | Hijo | Cobertura | Confianza |")
doc03_lines.append("|---|---|---|---:|:---:|")
doc03_lines.append("| CIRUGIA → CLIENTE (patient) | CIRPACCOD | CLICOD | 7,359/7,360 = 99.99% | CONFIRMADA |")
doc03_lines.append("| CIRUGIA → CLIENTE (doctor) | CIRMEDCOD | CLICOD | 5,900/5,900 = 100% | CONFIRMADA |")
doc03_lines.append("| CIRUGIA → CLIENTE (hospital) | CIRHOSCOD | CLICOD | 4,686/4,687 = 99.99% | CONFIRMADA |")
doc03_lines.append("| CIRUGIA → CLIENTE (payer) | CIROSCOD | CLICOD | 7,512/7,512 = 100% | CONFIRMADA |")
doc03_lines.append("| CIRUGIA → CIRTIP | CIRTIP | 2,782/2,782 = 100% (37% de cirugías) | ALTA |")
doc03_lines.append("| CIRUGIA → VIAJANTE | VIACOD | 5,652/5,652 (75%); falta catálogo 'LET' en algunas | MEDIA |")
doc03_lines.append("| CIRUGIA → STOCK | CIRCOD → STKCIRCOD | 5,822/7,512 = 77.5% | CONFIRMADA |")
doc03_lines.append("| CIRUGIA → CUENTAS | CIRCOD → VTACIRCOD | 7,413 matches en 2,577 cirugías 2026 = 99.5% | CONFIRMADA |")
doc03_lines.append("| STOCK → STOCK1 | STKCOD | 1:N | CONFIRMADA |")
doc03_lines.append("| STOCK → CUENTAS | STKVTACOD → VTACOD | 8,666/9,754 = 88.9% | CONFIRMADA |")
doc03_lines.append("| CUENTAS → CUENTASD | VTACOD | 1:N (avg 3.0, max 22) | CONFIRMADA |")
doc03_lines.append("| CLIENTE → CLIATRI | CLICOD | 1:N atributos EAV | CONFIRMADA |")
doc03_lines.append("| ARTICULO → ARTATRI | ARTCOD | 1:N atributos EAV | CONFIRMADA |")
doc03_lines.append("| CUENTAS → CLIENTE | CLICOD | 100% match | CONFIRMADA |")
doc03_lines.append("| STOCK → CLIENTE | CLICOD | 9,110/9,754 = 93.4% | CONFIRMADA |")

(OUT_DIR / "03_MODELO_LEGACY.md").write_text("\n".join(doc03_lines), encoding="utf-8")
print("Wrote 03")

# ════════════════════════════════════════════════════════════════════
# Documento 04: Cirugías 2026
# ════════════════════════════════════════════════════════════════════
doc04_lines = []
doc04_lines.append("# 04 — Cirugías 2026 (Análisis Independiente)")
doc04_lines.append("")
doc04_lines.append("## Resumen ejecutivo")
doc04_lines.append("")
total = sum(cir2026['cir_2026_counts'].values())
a_count = cir2026['cir_2026_counts']
doc04_lines.append(f"**Total cirugías cargadas con CIRFECCAR o CIRFEC en 2026:** {total}")
doc04_lines.append("")
doc04_lines.append("## Distribución por estado (carga 2026)")
doc04_lines.append("")
doc04_lines.append("| Estado | Total 2026 | % | Interpretación XAdmin |")
doc04_lines.append("|-------|----------:|---:|---|")
doc04_lines.append(f"| SAU | {a_count['SAU']:,} | {100*a_count['SAU']/total:.1f}% | Sin Autorizar |")
doc04_lines.append(f"| FIN | {a_count['FIN']:,} | {100*a_count['FIN']/total:.1f}% | Finalizada (realizada + facturada) |")
doc04_lines.append(f"| CAN | {a_count['CAN']:,} | {100*a_count['CAN']/total:.1f}% | Cancelada |")
doc04_lines.append(f"| REA | {a_count['REA']:,} | {100*a_count['REA']/total:.1f}% | Realizada (con consumo) |")
doc04_lines.append(f"| TRA | {a_count['TRA']:,} | {100*a_count['TRA']/total:.1f}% | En Tránsito |")
doc04_lines.append(f"| AUT | {a_count['AUT']:,} | {100*a_count['AUT']/total:.1f}% | Autorizada |")
doc04_lines.append(f"| PEN | {a_count['PEN']:,} | {100*a_count['PEN']/total:.1f}% | Pendiente |")
doc04_lines.append(f"| SUS | {a_count['SUS']:,} | {100*a_count['SUS']/total:.1f}% | Suspendida |")
doc04_lines.append(f"| SCO | {a_count['SCO']:,} | {100*a_count['SCO']/total:.1f}% | Sin Consumo |")
doc04_lines.append("")
doc04_lines.append("## Distribución por mes (FECHA DE CIRUGÍA — cirfec)")
doc04_lines.append("")
doc04_lines.append("| Mes | Total | FIN | REA | CAN | SUS | SCO | TRA | AUT | PEN | SAU |")
doc04_lines.append("|-----|------:|----:|----:|----:|----:|----:|----:|----:|----:|----:|")
month_data = {k: v for k, v in cir2026["by_year_month_fec_cirugia"].items() if k.startswith("2026")}
for k in sorted(month_data.keys()):
    v = month_data[k]
    total_mes = sum(v.values())
    doc04_lines.append(f"| {k} | {total_mes} | {v.get('FIN', 0)} | {v.get('REA', 0)} | {v.get('CAN', 0)} | {v.get('SUS', 0)} | {v.get('SCO', 0)} | {v.get('TRA', 0)} | {v.get('AUT', 0)} | {v.get('PEN', 0)} | {v.get('SAU', 0)} |")
doc04_lines.append("")
doc04_lines.append("## Distribución por mes (FECHA DE CARGA — cirfeccar)")
doc04_lines.append("")
doc04_lines.append("| Mes | Total |")
doc04_lines.append("|-----|------:|")
month_carga = {k: v for k, v in cir2026["by_year_month_carga"].items() if k.startswith("2026")}
for k in sorted(month_carga.keys()):
    total_mes = sum(month_carga[k].values())
    doc04_lines.append(f"| {k} | {total_mes} |")
doc04_lines.append("")
doc04_lines.append("## Distribución por año (todas las cirugías)")
doc04_lines.append("")
doc04_lines.append("| Año carga | Total | FIN | REA | CAN | SUS | SCO | TRA | AUT | PEN | SAU |")
doc04_lines.append("|-----|------:|----:|----:|----:|----:|----:|----:|----:|----:|----:|")
for y in sorted(cir2026["by_year_estado"].keys()):
    v = cir2026["by_year_estado"][y]
    total_y = sum(v.values())
    doc04_lines.append(f"| {y} | {total_y} | {v.get('FIN', 0)} | {v.get('REA', 0)} | {v.get('CAN', 0)} | {v.get('SUS', 0)} | {v.get('SCO', 0)} | {v.get('TRA', 0)} | {v.get('AUT', 0)} | {v.get('PEN', 0)} | {v.get('SAU', 0)} |")
doc04_lines.append("")
doc04_lines.append("## Hallazgos")
doc04_lines.append("")
doc04_lines.append("- **REA es muy rara en este dataset (50 vs 1,068 FIN).** Esto NO concuerda con la semántica XAdmin de \"REA = con consumo cargado\". Posibles razones:")
doc04_lines.append("  - El sistema XAdmin marca REA brevemente y luego transiciona a FIN cuando se factura.")
doc04_lines.append("  - En 2024-2025 había más REA (1 en 2025) — los flujos se consolidan rápido a FIN.")
doc04_lines.append("- **SAU 1,199 (47%)**: casi mitad de cirugías 2026 no están autorizadas. Esto es esperable: muchas se cargan antes de obtener la autorización de la obra social.")
doc04_lines.append("- **CAN 132 (5.2%)**: nivel normal de cancelaciones.")
doc04_lines.append("- **SCO 7 (0.3%)**: 'Sin Consumo' es rarísimo — quizás indica registros incompletos.")
doc04_lines.append("- **Oct 2026 'fantasma': 21 cirugías** con cirfec en octubre 2026 — son programadas a futuro.")
doc04_lines.append("")
doc04_lines.append("## Dependencias pre-2026 necesarias para preservar integridad")
doc04_lines.append("")
doc04_lines.append("Para migrar las 2,577 cirugías 2026 con integridad referencial, también necesitamos importar:")
doc04_lines.append("")
doc04_lines.append("- **Pacientes** (7,360 CIRPACCOD distintos): todos los CLIENTE con `clicir` paciente activo.")
doc04_lines.append("- **Médicos** (434 CIRMEDCOD distintos): todos los CLIENTE referidos como doctor en cualquier cirugía (no solo 2026).")
doc04_lines.append("- **Hospitales** (135 CIRHOSCOD distintos): CLIENTE referidos como hospital en cualquier cirugía.")
doc04_lines.append("- **Obras sociales** (173 CIROSCOD distintos): CLIENTE referidos como payer.")
doc04_lines.append("- **Vendedores/coordinadores** (6 VIAJANTE: ADMIN, NELS, EZE, CRIS, FRA, SUCUR, LET).")
doc04_lines.append("- **Tipos de cirugía** (57 CIRTIP distintos en uso).")
doc04_lines.append("- **Stock/Remitos/Devoluciones/Facturas**: 5,822 STOCK con STKCIRCOD; 7,413 facturas CUENTAS con VTACIRCOD.")
doc04_lines.append("- **Artículos**: ~2,220 artículos distintos usados en CUENTASD 2026 (de 5,902 totales).")
doc04_lines.append("- **Notas**: 6,365 CIRNOTAS, todas con CIRCOD FK; 1,500-2,500 son de 2026.")

(OUT_DIR / "04_CIRUGIAS_2026.md").write_text("\n".join(doc04_lines), encoding="utf-8")
print("Wrote 04")
