"""Generate documents 05-06."""
import json
from pathlib import Path

OUT_DIR = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\docs\migration-consultar-plus\minimax-audit")
TMP = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\.tmp\consultar-plus-minimax-audit")


def load(name):
    with open(TMP / name, encoding="utf-8") as f:
        return json.load(f)


sf = load("05_stock_forensics.json")
stktip_c = load("05b_stktip_c.json")
devol_pat = load("06_devolucion_pattern.json")

# ════════════════════════════════════════════════════════════════════
# Documento 05: Forénsica STOCK/STOCK1
# ════════════════════════════════════════════════════════════════════
doc05_lines = []
doc05_lines.append("# 05 — Forénsica Profunda STOCK/STOCK1")
doc05_lines.append("")
doc05_lines.append("## Pregunta de investigación")
doc05_lines.append("")
doc05_lines.append("¿Qué significa cada combinación de STKTIP × STKES × STKDEV × STKCOM × MOVES?")
doc05_lines.append("")
doc05_lines.append("## Hallazgo principal")
doc05_lines.append("")
doc05_lines.append("**El término 'DEVOLUCIÓN' en este sistema NO significa 'devolución por cancelación'.**")
doc05_lines.append("El campo `STKCONCE` con valor `DEVOLUCIÓN - CONSUMO` aparece en el **retorno rutinario de material no usado después de una cirugía finalizada**, NO en la cancelación.")
doc05_lines.append("")
doc05_lines.append("## Diccionario inferido")
doc05_lines.append("")
doc05_lines.append("### Campos categóricos")
doc05_lines.append("")
doc05_lines.append("| Campo | Valores | Significado inferido |")
doc05_lines.append("|---|---|---|")
doc05_lines.append("| STKTIP | A | Alta (inicial / reserva) |")
doc05_lines.append("| STKTIP | B | Baja (entrega / salida) |")
doc05_lines.append("| STKTIP | C | Carga (reposición / ingreso) |")
doc05_lines.append("| STKES | E | Entrada al stock (retorno) |")
doc05_lines.append("| STKES | S | Salida del stock |")
doc05_lines.append("| STKDEV | S | Es devolución (reversión) |")
doc05_lines.append("| STKDEV | N | No es devolución |")
doc05_lines.append("| STKCOM | NR | Comprobante Normal (Reserva inicial pre-cirugía) |")
doc05_lines.append("| STKCOM | RE | Remito (retorno post-cirugía = DEVOLUCIÓN-CONSUMO) |")
doc05_lines.append("| STKCOM | AJ | Ajuste manual |")
doc05_lines.append("| STKCOM | TR | Tránsito entre depósitos |")
doc05_lines.append("| STKCOM | CV | Comprobante de venta (auto-factura) |")
doc05_lines.append("| STKCOM | FV | Factura de venta |")
doc05_lines.append("| STKCOM | TV | Transferencia |")
doc05_lines.append("| STKCOM | LV | Lista de venta |")
doc05_lines.append("| STKCOM | PE | Pedido especial |")
doc05_lines.append("| STKCOM | FC | ? (raro, 1 muestra) |")
doc05_lines.append("| STKCOM | CM | ? (raro, 2 muestras) |")
doc05_lines.append("| MOVES | E | Movimiento entrada |")
doc05_lines.append("| MOVES | S | Movimiento salida |")
doc05_lines.append("| MOVUNI | S | Unidad stock (cantidad física) |")
doc05_lines.append("| MOVUNI | V | Unidad venta (cantidad facturable) |")
doc05_lines.append("| MOVUNI | C | ? (1 muestra, ignorado) |")
doc05_lines.append("")
doc05_lines.append("### Distribución STOCK completo (9,754 registros)")
doc05_lines.append("")
doc05_lines.append("**STKTIP:**")
doc05_lines.append("- A (Alta): 2,623 (26.9%)")
doc05_lines.append("- B (Baja): 5,794 (59.4%)")
doc05_lines.append("- C (Carga): 1,335 (13.7%)")
doc05_lines.append("- Vacío: 2 (0.02%)")
doc05_lines.append("")
doc05_lines.append("**STKES:**")
doc05_lines.append("- E (Entrada): 3,193 (32.7%)")
doc05_lines.append("- S (Salida): 6,561 (67.3%)")
doc05_lines.append("")
doc05_lines.append("**STKDEV:**")
doc05_lines.append("- S (Devolución): 1,844 (18.9%)")
doc05_lines.append("- N: 4,746 (48.7%)")
doc05_lines.append("- Vacío: 3,164 (32.4%) — registros sin clasificar (probablemente AJ/TR/C)")
doc05_lines.append("")
doc05_lines.append("**STKCOM:**")
doc05_lines.append("- NR: 6,304 (64.6%)")
doc05_lines.append("- RE: 2,659 (27.3%)")
doc05_lines.append("- AJ: 572 (5.9%)")
doc05_lines.append("- TR: 97 (1.0%)")
doc05_lines.append("- CV: 69 (0.7%)")
doc05_lines.append("- FV: 41 (0.4%)")
doc05_lines.append("- Otros (TV/LV/FC/CM/PE): 12 (0.1%)")
doc05_lines.append("")
doc05_lines.append("### Combinaciones triple (STKTIP × STKES × STKDEV)")
doc05_lines.append("")
doc05_lines.append("| Triple | Registros | Interpretación |")
doc05_lines.append("|---|---:|---|")
triple = sf['stock']['triple']
# Sort by count
triple_sorted = sorted([(k, v) for k, v in triple.items()], key=lambda x: -x[1])
for k, v in triple_sorted:
    parts = k.split('|')
    tip, es, dev = parts
    interp = ""
    if tip == "B" and es == "S" and dev == "N":
        interp = "Salida normal (pre-cirugía o venta)"
    elif tip == "B" and es == "E" and dev == "S":
        interp = "**DEVOLUCIÓN - CONSUMO** (retorno post-cirugía)"
    elif tip == "A" and es == "S" and dev == "N":
        interp = "Salida desde Alta (entrega de material reservado)"
    elif tip == "A" and es == "E" and dev == "S":
        interp = "**DEVOLUCIÓN - CONSUMO** sobre Alta"
    elif tip == "C" and es == "S":
        interp = "Salida por Carga/Reposición (sin dev)"
    elif tip == "C" and es == "E" and dev == "N":
        interp = "Entrada por Carga/Reposición"
    elif tip == "B" and es == "S" and dev == "":
        interp = "Salida sin clasificar (probable AJ o TR)"
    doc05_lines.append(f"| {tip}×{es}×{dev} | {v:,} | {interp} |")
doc05_lines.append("")
doc05_lines.append("### Combinaciones con comprobante (surgery records)")
doc05_lines.append("")
doc05_lines.append("De los 5,338 STOCK records con STKCIRCOD:")
doc05_lines.append("")
doc05_lines.append("| Combo | Registros | Interpretación |")
doc05_lines.append("|---|---:|---|")
surg_combos = sf['stock']['surgery_stock_combos']
surg_sorted = sorted([(k, v) for k, v in surg_combos.items()], key=lambda x: -x[1])
for k, v in surg_sorted:
    parts = k.split('|')
    tip, es, dev, com = parts
    interp = ""
    if tip == "B" and es == "S" and dev == "N" and com == "NR":
        interp = "**SALIDA inicial pre-cirugía** (entrega material)"
    elif tip == "B" and es == "E" and dev == "S" and com == "RE":
        interp = "**DEVOLUCIÓN-CONSUMO post-cirugía**"
    elif tip == "A" and es == "S" and dev == "N" and com == "NR":
        interp = "Salida desde Alta"
    elif tip == "A" and es == "E" and dev == "S" and com == "RE":
        interp = "DEVOLUCIÓN-CONSUMO sobre Alta"
    doc05_lines.append(f"| {tip}×{es}×{dev}×{com} | {v:,} | {interp} |")
doc05_lines.append("")
doc05_lines.append("### STKCONCE patterns")
doc05_lines.append("")
doc05_lines.append("**Para B×E:**")
doc05_lines.append("- `DEVOLUCIÓN - CONSUMO` (literal, 1,843+ matches)")
doc05_lines.append("- Confirma: estos son retornos de material post-cirugía.")
doc05_lines.append("")
doc05_lines.append("**Para A×E:**")
doc05_lines.append("- `DEVOLUCIÓN - CONSUMO`")
doc05_lines.append("- Misma naturaleza.")
doc05_lines.append("")
doc05_lines.append("**Para B×S:**")
doc05_lines.append("- 'ORTOPEDIA' (cliente), 'Dr : SANTIANGO PIASSENTINI', 'SE ENTREGA A DROGUERIA CENTRAL', etc.")
doc05_lines.append("- Confirma: estas son salidas a clientes/pacientes.")
doc05_lines.append("")
doc05_lines.append("### STKTIP C en detalle")
doc05_lines.append("")
doc05_lines.append("1,335 registros STKTIP='C'. Distribución:")
doc05_lines.append(f"- STKES: E=265, S=1,070")
doc05_lines.append(f"- STKCOM: NR=1,064, RE=264, AJ=6, CV=1")
doc05_lines.append(f"- STKDEV: N=264, vacío=1,071")
doc05_lines.append("")
doc05_lines.append("**Observaciones OBS más comunes:**")
doc05_lines.append("- `ANULADO ((1075) PROVEEDOR PARA REALIZAR MODIFICACIONES)` (4)")
doc05_lines.append("- `REMITO : 88235` (2)")
doc05_lines.append("- `MOVIMIENTO OPUESTO DE RE-C-4-16` (2) — auto-reversión")
doc05_lines.append("- `TOR-4.5-7.0-CANU-TIT-002` (2)")
doc05_lines.append("- `CARGA DE REPO` (2)")
doc05_lines.append("- `INGRESO A SISTEMA` (1)")
doc05_lines.append("- `CARGA DE IMPLANTES` (1)")
doc05_lines.append("- `INGRESO DIA SABADO 27/07` (1)")
doc05_lines.append("")
doc05_lines.append("**Conclusión sobre STKTIP C:** Probablemente:")
doc05_lines.append("- C+S+NR (1,070): salida por carga inicial (materia prima / compra)")
doc05_lines.append("- C+E+N+RE (264): entrada por carga con devolución posterior (anulación)")
doc05_lines.append("- C+E+NR (1): carga pura")
doc05_lines.append("- C+S+AJ (6): ajuste de salida")
doc05_lines.append("")
doc05_lines.append("### STOCK1 sample (30,000 registros)")
doc05_lines.append("")
doc05_lines.append("**MOVES:**")
doc05_lines.append("- E: 16,824 (56.1%)")
doc05_lines.append("- S: 13,176 (43.9%)")
doc05_lines.append("")
doc05_lines.append("**MOVUNI:**")
doc05_lines.append("- S (stock unit): 19,153 (63.8%)")
doc05_lines.append("- V (venta unit): 10,846 (36.1%)")
doc05_lines.append("- C: 1")
doc05_lines.append("")
doc05_lines.append("**MOVES × MOVUNI (clave para entender consumo):**")
doc05_lines.append("- E×S: 16,124 (entrada en unidad stock — devolución física)")
doc05_lines.append("- S×V: 10,147 (salida en unidad venta — entrega facturada)")
doc05_lines.append("- S×S: 3,029 (salida en unidad stock — entrega física sin facturar)")
doc05_lines.append("- E×V: 699 (entrada en unidad venta — extraño; ver anomalías)")
doc05_lines.append("")
doc05_lines.append("**MOVES × MOVCER:**")
doc05_lines.append("- E×(vacío): 16,187 — entradas sin clasificar")
doc05_lines.append("- S×(vacío): 4,329 — salidas sin clasificar")
doc05_lines.append("- S×S: 8,257 — salidas cerradas")
doc05_lines.append("- S×N: 590 — salidas abiertas")
doc05_lines.append("- E×N: 473 — entradas abiertas")
doc05_lines.append("- E×S: 164 — entradas cerradas")
doc05_lines.append("")
doc05_lines.append("**MOVSTKCOD (reversa):**")
doc05_lines.append("- 6,645 con STKCOD de referencia (reversiones explícitas)")
doc05_lines.append("- 23,355 sin STKCOD (movimientos independientes)")
doc05_lines.append("")
doc05_lines.append("**MOVCAN negativos:**")
doc05_lines.append("- Rango observado: -1 a 81,600")
doc05_lines.append("- El `-1` aparece (probable flag de anulación)")
doc05_lines.append("")
doc05_lines.append("## Conclusiones forénsicas")
doc05_lines.append("")
doc05_lines.append("1. **El modelo STOCK/STOCK1 codifica un sistema de remitos + devoluciones con doble entrada:**")
doc05_lines.append("   - `STKCOM='NR' + STKTIP='B' + STKES='S' + STKDEV='N'`: salida inicial (entrega al cliente/paciente) → genera STOCK1 con MOVES='S', MOVUNI='V' (facturable).")
doc05_lines.append("   - `STKCOM='RE' + STKTIP='B' + STKES='E' + STKDEV='S'`: devolución-consumo (retorno de no usado) → STOCK1 con MOVES='E', MOVUNI='S' (devuelto a stock físico).")
doc05_lines.append("   - El STOCK1 hijo del NR referencia `stkref` al STOCK1 hijo del RE (vía MOVSTKCOD/MOVMOVORD) para trazabilidad por artículo.")
doc05_lines.append("")
doc05_lines.append("2. **OSSUM debe separar los conceptos:**")
doc05_lines.append("   - `Remito` ← STOCK (NR) + STOCK1 (MOVES=S, MOVUNI=V)")
doc05_lines.append("   - `Consumo` ← diferencia implícita: cantidad enviada - cantidad devuelta (por artículo)")
doc05_lines.append("   - `Devolucion` ← STOCK (RE) + STOCK1 (MOVES=E, MOVUNI=S)")
doc05_lines.append("   - `StockMovement` ← cada STOCK1 produce 2 StockMovement: RECEIPT_IN (entrada) o RETURN_IN (devolución), con FK a remito/consumo/devolucion según corresponda.")
doc05_lines.append("")
doc05_lines.append("3. **NO hay remito separado del modelo STOCK.** El 'remito' ES un STOCK con STKCOM='RE'. La numeración de remitos no es global sino por-STKCOM.")

(OUT_DIR / "05_FORENSICA_STOCK.md").write_text("\n".join(doc05_lines), encoding="utf-8")
print("Wrote 05")

# ════════════════════════════════════════════════════════════════════
# Documento 06: Facturación y Remitos
# ════════════════════════════════════════════════════════════════════
doc06_lines = []
doc06_lines.append("# 06 — Facturación y Remitos (Análisis Independiente)")
doc06_lines.append("")
doc06_lines.append("## Pregunta")
doc06_lines.append("")
doc06_lines.append("1. ¿Cómo se vincula CIRUGIA → FACTURA en el legacy?")
doc06_lines.append("2. ¿Qué distingue una factura de FIN vs REA vs CAN/SUS?")
doc06_lines.append("3. ¿Existe una entidad 'remito' separada o vive dentro de STOCK?")
doc06_lines.append("")
doc06_lines.append("## Hallazgos clave")
doc06_lines.append("")
doc06_lines.append("### 1. Doble vínculo CIRUGIA → FACTURA")
doc06_lines.append("")
doc06_lines.append("El legacy tiene **dos FKs** entre CIRUGIA y CUENTAS:")
doc06_lines.append("")
doc06_lines.append("- **Directo:** `CUENTAS.VTACIRCOD` (N 7) → `CIRUGIA.CIRCOD`")
doc06_lines.append("- **Indirecto (vía STOCK):** `STOCK.STKVTACOD` → `CUENTAS.VTACOD` y `STOCK.STKCIRCOD` → `CIRUGIA.CIRCOD`")
doc06_lines.append("")
doc06_lines.append("La redundancia confirma el modelo. Para OSSUM, debe haber UNA FK limpia (probablemente la directa).")
doc06_lines.append("")
doc06_lines.append("### 2. Cobertura")
doc06_lines.append("")
doc06_lines.append("Para 2,577 cirugías 2026:")
doc06_lines.append("")
doc06_lines.append("| Estado | Con factura | Sin factura | Total | Cobertura |")
doc06_lines.append("|-------|---:|---:|---:|---:|")
fin = load("09_facturacion.json")
estados = fin['cir_2026_by_estado']
with_vta = fin['cir_2026_with_vta_by_estado']
for est in ["SAU", "AUT", "PEN", "TRA", "REA", "FIN", "CAN", "SUS", "SCO"]:
    doc06_lines.append(f"| {est} | {with_vta.get(est, 0)} | {estados.get(est, 0) - with_vta.get(est, 0)} | {estados.get(est, 0)} | {100*with_vta.get(est, 0)/max(estados.get(est, 0), 1):.1f}% |")
doc06_lines.append("")
doc06_lines.append("**Observación:** casi TODAS las cirugías 2026 tienen al menos 1 factura asociada (99.5%). Las excepciones (13) son cirugías canceladas/sin avance.")
doc06_lines.append("")
doc06_lines.append("Esto NO significa que estén facturadas en sentido fiscal. La factura se crea automáticamente al cargar la cirugía (en estado Borrador interno) y se actualiza durante el workflow.")
doc06_lines.append("")
doc06_lines.append("### 3. VTAs por cirugía")
doc06_lines.append("")
doc06_lines.append("| # VTAs | Cirugías 2026 |")
doc06_lines.append("|------:|---:|")
vta_count = fin['cir_vta_count_dist']
for k, v in sorted(vta_count.items(), key=lambda x: int(x[0])):
    doc06_lines.append(f"| {k} | {v:,} |")
doc06_lines.append("")
doc06_lines.append("**Observación:** la mayoría de cirugías (1,167) tienen 1 sola factura, pero hay un número significativo con múltiples facturas (289 con 2, 254 con 3, 465 con 4, 230 con 5...). Esto sugiere que el sistema crea varias versiones de la factura a lo largo del workflow (ej: borrador → impresión → anulación → NC).")
doc06_lines.append("")
doc06_lines.append("### 4. CUENTASD (líneas de factura)")
doc06_lines.append("")
doc06_lines.append("- 56,021 líneas para 22,029 facturas")
doc06_lines.append("- Promedio: 2.5 líneas por factura")
doc06_lines.append("- Para facturas FIN 2026: avg=3.0 líneas, max=22, n=4,729")
doc06_lines.append("- 2,220 artículos distintos facturados (de 5,902 totales = 37.6%)")
doc06_lines.append("")
doc06_lines.append("### 5. VTATIP y VTACAI (discriminación fiscal)")
doc06_lines.append("")
doc06_lines.append("- `VTATIP`: A=Factura A, B=Factura B, C=Factura C")
doc06_lines.append(f"  - VTATIP distribución total: A={fin['vta_tipos'].get('A', 0)}, B={fin['vta_tipos'].get('B', 0)}, C={fin['vta_tipos'].get('C', 0)}")
doc06_lines.append("- `VTACAI`: 14-char CAE AFIP — presente en facturas autorizadas, vacío en borradores")
doc06_lines.append("- `VTAIMP`: S impresa, vacío no impresa")
doc06_lines.append("- `VTAELE`: S electrónica (post-RG 4291/2018)")
doc06_lines.append("- `VTACPTEV`: V=Venta, C=Cancel/Anulación")
doc06_lines.append("")
doc06_lines.append("### 6. Distribución por estado de cirugía")
doc06_lines.append("")
doc06_lines.append("Para CIRUGIA FIN 2026 (4,718 facturas):")
doc06_lines.append("")
doc06_lines.append("| Campo | S | N | Vacío | Total |")
doc06_lines.append("|---|---:|---:|---:|---:|")
doc06_lines.append("| VTAIMP (impresa) | 1,955 | - | 2,763 | 4,718 |")
doc06_lines.append("| VTAELE (electrónica) | 1,172 | 282 | 3,264 | 4,718 |")
doc06_lines.append("| VTAESTCOM (estado comprobante) | 2,077 | - | 2,641 | 4,718 |")
doc06_lines.append("| VTACAI presente (CAE) | ~50 con CAE | - | resto | 4,718 |")
doc06_lines.append("| VTACPTEV=V (venta) | 3,390 | - | 1,328 | 4,718 |")
doc06_lines.append("| VTACPTEV=C (cancel/anul) | 470 | - | - | 470 |")
doc06_lines.append("")
doc06_lines.append("**Interpretación:** Solo ~2,077 facturas en FIN tienen estado comprobante 'S' (cerrado). Las 2,641 sin clasificar probablemente son pre-impresión o intermedias. ~50 tienen CAE (fiscalmente autorizadas).")
doc06_lines.append("")
doc06_lines.append("### 7. NO distinción neta FIN vs REA en facturas")
doc06_lines.append("")
doc06_lines.append("**Sorpresa mayor:** la diferencia entre FIN y REA en el modelo de facturas es **casi nula**. Ambos tienen:")
doc06_lines.append("- 100% cobertura de facturas")
doc06_lines.append("- Distribución similar de VTATIP A/B")
doc06_lines.append("- Cantidad comparable de CAE")
doc06_lines.append("")
doc06_lines.append("**Conclusión:** REA y FIN probablemente difieren solo en metadata interna, no en la factura. La distinción real es REA = 'lista para facturar', FIN = 'facturada formalmente'.")
doc06_lines.append("")
doc06_lines.append("### 8. CIRUGIA CAN/SUS/SCO también tienen facturas")
doc06_lines.append("")
doc06_lines.append("- CAN: 100% con factura")
doc06_lines.append("- SUS: 100% con factura")
doc06_lines.append("- SCO: 100% con factura")
doc06_lines.append("")
doc06_lines.append("Pero pocas con CAE (autorización fiscal):")
doc06_lines.append("- CAN con CAE: ~7 (de 286 facturas)")
doc06_lines.append("- SUS: 0 con CAE")
doc06_lines.append("- SCO: 1 con CAE")
doc06_lines.append("")
doc06_lines.append("**Interpretación:** Para cirugías canceladas, la factura original NO se anula fiscalmente — simplemente queda en estado 'sin consumar' o se genera una NC.")
doc06_lines.append("")
doc06_lines.append("## REMITOS")
doc06_lines.append("")
doc06_lines.append("### No existe tabla separada de remitos")
doc06_lines.append("")
doc06_lines.append("Búsqueda exhaustiva:")
doc06_lines.append("- Tablas con REMIT/REMITO/ENTRE/LOGIST en nombre: **0 resultados**")
doc06_lines.append("- `REPARTO` (1 registro) y `REPARTO1` (3 registros): tablas de reparto casi vacías; solo un experimento abortado")
doc06_lines.append("")
doc06_lines.append("### El remito vive dentro de STOCK")
doc06_lines.append("")
doc06_lines.append("El **remito es un STOCK con STKCOM='RE'** (Remito):")
doc06_lines.append("- STOCK.STKCOD = ID del remito")
doc06_lines.append("- STOCK.STKVTACOD = factura asociada")
doc06_lines.append("- STOCK.STKCIRCOD = cirugía asociada")
doc06_lines.append("- STOCK1.STKCOD/MOVORD = líneas del remito")
doc06_lines.append("- STOCK.STKVTACOD != 0 → factura asociada")
doc06_lines.append("- STOCK.STKFEC = fecha del remito")
doc06_lines.append("")
doc06_lines.append("Numeración:")
doc06_lines.append("- `STK.STKNRO` (N 8) = número del comprobante (dentro de STKCOM='RE', secuencia propia)")
doc06_lines.append("- Cada `STKCOM` tiene su propia numeración")
doc06_lines.append("")
doc06_lines.append("### Para OSSUM")
doc06_lines.append("")
doc06_lines.append("Mapping:")
doc06_lines.append("- 1 STOCK (STKCOM='RE') → 1 OSSUM `Remito`")
doc06_lines.append("- 1 STOCK1 línea → 1 OSSUM `RemitoItem`")
doc06_lines.append("- La factura (CUENTAS) está asociada vía OSSUM `Invoice` con `consumoId` o `presupuestoId`")
doc06_lines.append("- En OSSUM, `Remito.surgeryId` se llena; el STOCK previo (STKCOM='NR') NO genera Remito separado (es la reserva, no el envío).")
doc06_lines.append("")
doc06_lines.append("**Decisión recomendada:** mapear SOLO STOCK(STKCOM='RE') como Remito. El STOCK(STKCOM='NR') se descarta o se usa para reconstruir el evento 'preparación'.")
doc06_lines.append("")
doc06_lines.append("### 9. Anomalías / riesgos")
doc06_lines.append("")
doc06_lines.append("- **Múltiples facturas idénticas** (mismo total, fechas cercanas): evidencia de workflow de impresión + anulación. OSSUM debe deduplicar o preservar histórico completo.")
doc06_lines.append("- **FK inversa `REPNRO`** en CUENTAS y STOCK: tabla `REPARTO` con 1 registro es evidencia de un feature abandonado. No debería migrarse.")

(OUT_DIR / "06_FACTURACION_REMITOS.md").write_text("\n".join(doc06_lines), encoding="utf-8")
print("Wrote 06")
