"""Generate documents 10-12."""
import json
from pathlib import Path

OUT_DIR = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\docs\migration-consultar-plus\minimax-audit")
TMP = Path(r"E:\OSSUM_COR_ANTIGRAVITY\ux-ui\.tmp\consultar-plus-minimax-audit")


def load(name):
    with open(TMP / name, encoding="utf-8") as f:
        return json.load(f)


# ════════════════════════════════════════════════════════════════════
# Documento 10: Migration Readiness OSSUM
# ════════════════════════════════════════════════════════════════════
doc10_lines = []
doc10_lines.append("# 10 — Migration Readiness OSSUM (Análisis Independiente)")
doc10_lines.append("")
doc10_lines.append("## Estado actual del OSSUM para soportar migración")
doc10_lines.append("")
doc10_lines.append("### Lo que YA soporta el schema")
doc10_lines.append("")
doc10_lines.append("OSSUM tiene las entidades clave:")
doc10_lines.append("- `Organization` / `Company` (multitenancy)")
doc10_lines.append("- `Surgery` con `cxStatus`, `prepStatus`, `materialShippingDate`, `materialAvailabilityDate`, `materialTransport`")
doc10_lines.append("- `Contact` + `ContactCompanyLink` con roles múltiples, `doctorLicense`, `specialty`, `usualDiscount`, `paymentTerms`, `vatCondition`")
doc10_lines.append("- `ContactGroup` + `ContactGroupMembership`")
doc10_lines.append("- `Remito` + `RemitoItem` (con lot/serial/expiration)")
doc10_lines.append("- `Consumo` + `ConsumoItem` (con `requestedQuantity` vs `consumedQuantity`)")
doc10_lines.append("- `Devolucion` + `DevolucionItem`")
doc10_lines.append("- `Presupuesto` + `PresupuestoItem` (Fase 1C)")
doc10_lines.append("- `Invoice` + `InvoiceItem` (operacional, no fiscal)")
doc10_lines.append("- `FiscalDocument` + `FiscalIssuanceAttempt` (DEV_ONLY snapshot)")
doc10_lines.append("- `Payment` + `PaymentImputation`")
doc10_lines.append("- `Article` + `ArticleIdentifier` + `ArticleSupplierMapping`")
doc10_lines.append("- `StockMovement` con idempotencyKey")
doc10_lines.append("- `NecesidadCompra`")
doc10_lines.append("- `AuditEvent`")
doc10_lines.append("- `SeguimientoEntry`")
doc10_lines.append("- `DigitalReceipt`")
doc10_lines.append("")
doc10_lines.append("### Lo que el schema actual NO soporta explícitamente")
doc10_lines.append("")
doc10_lines.append("Para una migración histórica segura, OSSUM debería tener (o aceptar) los siguientes elementos:")
doc10_lines.append("")
doc10_lines.append("#### A) Identidad legacy")
doc10_lines.append("")
doc10_lines.append("Necesitamos preservar el ID legacy (`CIRCOD`, `CLICOD`, `ARTCOD`, `VTACOD`, `STKCOD`) para:")
doc10_lines.append("- Reconciliación posterior")
doc10_lines.append("- Auditoría")
doc10_lines.append("- Rollback")
doc10_lines.append("- Queries de 'qué se migró'")
doc10_lines.append("")
doc10_lines.append("**Decisión recomendada: ledger transversal vs columna directa.**")
doc10_lines.append("")
doc10_lines.append("Opción A: columna directa en cada tabla")
doc10_lines.append("- Pros: simple, query directa")
doc10_lines.append("- Contras: no escala a multi-fuente legacy, ocupa siempre espacio")
doc10_lines.append("")
doc10_lines.append("Opción B: ledger transversal `LegacyEntityRef`")
doc10_lines.append("- Pros: soporta múltiples fuentes (legacy Districorr, futuras, etc.)")
doc10_lines.append("- Pros: puede llevar metadata (fecha de migración, runId, hash)")
doc10_lines.append("- Contras: requiere join para obtener el ID legacy")
doc10_lines.append("")
doc10_lines.append("**Recomendación:** Opción B. Crear tabla:")
doc10_lines.append("")
doc10_lines.append("```")
doc10_lines.append("model LegacyEntityRef {")
doc10_lines.append("  id          String   @id @default(cuid())")
doc10_lines.append("  companyId   String")
doc10_lines.append("  source      String   // 'districorr_backup_20260929'")
doc10_lines.append("  entityType  String   // 'Surgery' | 'Contact' | 'Invoice' | ...")
doc10_lines.append("  legacyId    String   // CIRCOD, CLICOD, etc.")
doc10_lines.append("  entityId    String   // OSSUM CUID")
doc10_lines.append("  migratedAt  DateTime @default(now())")
doc10_lines.append("  migrationRunId String")
doc10_lines.append("  metadata    Json?")
doc10_lines.append("  @@unique([source, entityType, legacyId])")
doc10_lines.append("  @@index([companyId, entityType, entityId])")
doc10_lines.append("}")
doc10_lines.append("```")
doc10_lines.append("")
doc10_lines.append("#### B) Idempotencia y migrationRunId")
doc10_lines.append("")
doc10_lines.append("- `StockMovement.idempotencyKey` YA existe")
doc10_lines.append("- Falta: `MigrationRun` entity con runId, status, counters, errors")
doc10_lines.append("")
doc10_lines.append("```")
doc10_lines.append("model MigrationRun {")
doc10_lines.append("  id          String   @id @default(cuid())")
doc10_lines.append("  companyId   String")
doc10_lines.append("  source      String   // 'districorr_backup_20260929'")
doc10_lines.append("  startedAt   DateTime")
doc10_lines.append("  finishedAt  DateTime?")
doc10_lines.append("  status      String   // 'running'|'success'|'failed'|'partial'")
doc10_lines.append("  totalCount  Int")
doc10_lines.append("  successCount Int")
doc10_lines.append("  errorCount  Int")
doc10_lines.append("  errors      Json?    // array de {entityType, legacyId, error}")
doc10_lines.append("  metadata    Json?")
doc10_lines.append("}")
doc10_lines.append("")
doc10_lines.append("model MigrationError {")
doc10_lines.append("  id          String   @id @default(cuid())")
doc10_lines.append("  runId       String")
doc10_lines.append("  entityType  String")
doc10_lines.append("  legacyId    String")
doc10_lines.append("  errorMsg    String")
doc10_lines.append("  errorDetail Json?")
doc10_lines.append("  createdAt   DateTime @default(now())")
doc10_lines.append("  @@index([runId])")
doc10_lines.append("}")
doc10_lines.append("```")
doc10_lines.append("")
doc10_lines.append("#### C) Rollback")
doc10_lines.append("")
doc10_lines.append("- El ledger transversal permite rollback quirúrgico: borrar todos los entity con `migrationRunId=X`")
doc10_lines.append("- No requiere esquema adicional")
doc10_lines.append("- Se debe poder correr el script de rollback con un runId")
doc10_lines.append("")
doc10_lines.append("#### D) Reconciliación")
doc10_lines.append("")
doc10_lines.append("Necesitamos queries que permitan:")
doc10_lines.append("- \"Mostrame qué cirugías 2026 están en OSSUM y cuáles no\"")
doc10_lines.append("- \"Mostrame qué artículos referidos por cirugías 2026 están en OSSUM\"")
doc10_lines.append("- \"Mostrame diferencias de totales\"")
doc10_lines.append("")
doc10_lines.append("Estas queries se hacen con LEFT JOIN entre el ID legacy y el entityId OSSUM.")
doc10_lines.append("")
doc10_lines.append("#### E) Estados históricos")
doc10_lines.append("")
doc10_lines.append("- `Surgery.cancelledDate` ya existe")
doc10_lines.append("- `Surgery.archivedAt` ya existe")
doc10_lines.append("- Falta `Surgery.performedDate` para distinguir REA de FIN (si se necesita)")
doc10_lines.append("- `Surgery.archiveReason` para cirugías migradas con problemas")
doc10_lines.append("")
doc10_lines.append("Para el legacy, podemos usar:")
doc10_lines.append("- `performedDate` = cirfec cuando cirestado ∈ (REA, FIN, SCO)")
doc10_lines.append("- `cancelledDate` = cirfec cuando cirestado ∈ (CAN, SUS)")
doc10_lines.append("")
doc10_lines.append("#### F) Side effects de la migración")
doc10_lines.append("")
doc10_lines.append("OSSUM tiene side effects importantes que requieren cuidado:")
doc10_lines.append("- `StockMovement.quantity` afecta stock actual")
doc10_lines.append("- `Invoice.base='manual'` requiere generación de número")
doc10_lines.append("- `Remito.estado='Borrador'` por defecto; debe transicionar")
doc10_lines.append("- `Consumo.remitoId` FK obligatoria")
doc10_lines.append("- `Devolucion.remitoId` FK obligatoria")
doc10_lines.append("- `Invoice.consumoId` FK opcional (legacy puede no tener)")
doc10_lines.append("")
doc10_lines.append("**Recomendación:** para cirugías migradas, generar `Remito.estado='Cerrado'` directamente (no borrador), `Consumo.estado='Validado'` o 'Facturado' según legacy, etc.")
doc10_lines.append("")
doc10_lines.append("#### G) Tenant/Company")
doc10_lines.append("")
doc10_lines.append("- `EMPRESA.DBF` tiene 2 empresas: PRINC (DISTRICORR SRL) y TEST")
doc10_lines.append("- OSSUM es multi-tenant via `Company`")
doc10_lines.append("- Recomendación: crear 2 OSSUM `Company` (PRINC + TEST), mapear EMPCOD → Company.id")
doc10_lines.append("- El campo `EMPRESA.EMPPCAL='S'` indica cuál es la principal")
doc10_lines.append("")
doc10_lines.append("#### H) Contactos necesarios")
doc10_lines.append("")
doc10_lines.append("Para migrar 2,577 cirugías 2026:")
doc10_lines.append("- **Pacientes:** 7,360 CIRPACCOD distintos (subset de 9,078 CLIENTE)")
doc10_lines.append("- **Médicos:** 434 CIRMEDCOD distintos (subset)")
doc10_lines.append("- **Hospitales:** 135 CIRHOSCOD distintos")
doc10_lines.append("- **Payers:** 173 CIROSCOD distintos")
doc10_lines.append("- **Vendedores:** 7 VIAJANTE")
doc10_lines.append("- **Total únicos:** ~8,000 CONTACTOS (muchos son intersecciones de roles)")
doc10_lines.append("")
doc10_lines.append("Recomendación: importar TODOS los CLIENTE primero (9,078), luego enriquecer con CLIATRI y asignar roles via ContactCompanyLink.")
doc10_lines.append("")
doc10_lines.append("#### I) Artículos")
doc10_lines.append("")
doc10_lines.append("- **Total ARTICULO:** 5,902")
doc10_lines.append("- **Usados en cirugías 2026:** ~2,220 (37.6%)")
doc10_lines.append("- **Con ATRIENT:** 190,270")
doc10_lines.append("- **Con FORMULA1:** 94,735")
doc10_lines.append("")
doc10_lines.append("Recomendación: importar TODOS los 5,902 ARTICULO + sus ARTATRI + FORMULA1.")
doc10_lines.append("")
doc10_lines.append("### Resumen de schema changes recomendados")
doc10_lines.append("")
doc10_lines.append("Mínimos viables:")
doc10_lines.append("1. Agregar `model LegacyEntityRef` (transversal)")
doc10_lines.append("2. Agregar `model MigrationRun` y `model MigrationError`")
doc10_lines.append("3. Verificar si `Surgery.performedDate` debe distinguirse de `surgeryDate`")
doc10_lines.append("")
doc10_lines.append("NO necesarios (OSSUM ya cubre):")
doc10_lines.append("- Invoice, Remito, Consumo, Devolucion, Contact, Article, StockMovement — todos presentes")

(OUT_DIR / "10_READINESS.md").write_text("\n".join(doc10_lines), encoding="utf-8")
print("Wrote 10")

# ════════════════════════════════════════════════════════════════════
# Documento 11: Comparación Codex vs Minimax (placeholder hasta Fase 17)
# ════════════════════════════════════════════════════════════════════
doc11_lines = []
doc11_lines.append("# 11 — Comparación Codex vs Minimax")
doc11_lines.append("")
doc11_lines.append("## Estado: PENDIENTE hasta Fase 17")
doc11_lines.append("")
doc11_lines.append("Este documento se completará DESPUÉS de leer el análisis previo del agente Codex en:")
doc11_lines.append("")
doc11_lines.append("- (Carpeta fuente del agente previo: `E:\\OSSUM_COR_PROJECT\\docs\\migration-consultar-plus\\`)")
doc11_lines.append("- Documentos a revisar: `01_*` a `10_*` y `09_AUDITORIA_PROFUNDA_LEGACY.md`")
doc11_lines.append("")
doc11_lines.append("## Lo que ya tengo listo (MiniMax-M3, este análisis):")
doc11_lines.append("")
doc11_lines.append("- Inventario completo 510 DBF, 1.88M registros")
doc11_lines.append("- Modelo legacy con FKs verificadas (CIRUGIA → STOCK → CUENTAS)")
doc11_lines.append("- Cirugías 2026: 2,539 cargadas, 1,172 ocurrieron en 2026")
doc11_lines.append("- STOCK/STOCK1 forénsica: 1,844 devoluciones-consumo")
doc11_lines.append("- Facturación: 99.5% cirugías 2026 con invoice")
doc11_lines.append("- Mapping legacy → OSSUM con confianza por campo")
doc11_lines.append("- Clasificación A/B/C/D: 1,766 A + 759 B + 52 C + 0 D")
doc11_lines.append("- Auditoría adversarial: pasó en unicidad, fechas, FK")
doc11_lines.append("- Migration readiness: schema OK + recomendaciones de ledger transversal")
doc11_lines.append("")
doc11_lines.append("## Lo que falta")
doc11_lines.append("")
doc11_lines.append("- Leer 3 documentos previos: ANALISIS_2026.md, INVENTARIO_BACKUP.md, DICCIONARIO_DBF_RECONSTRUIDO.md")
doc11_lines.append("- Identificar acuerdos y discrepancias")
doc11_lines.append("- Para cada discrepancia: diseñar prueba READ-ONLY para resolver con datos")
doc11_lines.append("- Construir la matriz final")

(OUT_DIR / "11_COMPARACION_CODEX_MINIMAX.md").write_text("\n".join(doc11_lines), encoding="utf-8")
print("Wrote 11 (placeholder)")

# ════════════════════════════════════════════════════════════════════
# Documento 12: Conclusiones Finales
# ════════════════════════════════════════════════════════════════════
doc12_lines = []
doc12_lines.append("# 12 — Conclusiones Finales (Independientes)")
doc12_lines.append("")
doc12_lines.append("## TL;DR")
doc12_lines.append("")
doc12_lines.append("1. **El backup legacy es un sistema Visual FoxPro con 510 tablas DBF y ~1.88M registros.** La cirugía es un módulo menor (7,512 registros) en un sistema dominado por stock (312K movs) y contabilidad (90K líneas).")
doc12_lines.append("")
doc12_lines.append("2. **Para cirugías 2026, hay 2,539 cirugías CARGADAS y 1,172 que ocurrieron efectivamente.** Las 1,367 restantes son programadas a futuro (SAU/AUT/PEN/TRA).")
doc12_lines.append("")
doc12_lines.append("3. **El modelo STOCK/STOCK1 codifica remitos + devoluciones dentro del mismo sistema.** STKCOM='NR' es la salida inicial (reserva); STKCOM='RE' es el remito (entrega + posible devolución-consumo). No existe tabla separada de remitos.")
doc12_lines.append("")
doc12_lines.append("4. **El término 'DEVOLUCIÓN' en legacy NO es cancelación.** Es el retorno rutinario de material no usado tras una cirugía finalizada. NO se observan devoluciones por cancelación (CAN/SUS/SCO) — el sistema solo cambia el estado.")
doc12_lines.append("")
doc12_lines.append("5. **Casi TODAS las cirugías (99.5%) tienen factura asociada**, incluso las canceladas. El sistema crea la factura al cargar la cirugía, en estado borrador.")
doc12_lines.append("")
doc12_lines.append("6. **OSSUM está bien preparado** para recibir la migración. Faltan: (a) tabla `LegacyEntityRef` para ledger transversal, (b) `MigrationRun/Error` para tracking.")
doc12_lines.append("")
doc12_lines.append("7. **Clasificación final:** 1,766 A (alta) + 759 B (transformación) + 52 C (validación humana) + 0 D (no migrar) = 2,577 cirugías 2026.")
doc12_lines.append("")
doc12_lines.append("## Hallazgos críticos detallados")
doc12_lines.append("")
doc12_lines.append("### CIRUGIA: el núcleo")
doc12_lines.append("")
doc12_lines.append("- 7,512 cirugías totales (2004-2026)")
doc12_lines.append("- 43 campos, 1 sola PK (CIRCOD)")
doc12_lines.append("- 9 estados: SAU (47%), FIN (44%), CAN (5%), SUS (1.5%), AUT (0.8%), REA (0.7%), TRA (0.4%), PEN (0.3%), SCO (0.2%)")
doc12_lines.append("- 4 FKs a CLIENTE (paciente/doctor/hospital/payer) con 99.99% match")
doc12_lines.append("- Sin duplicados, sin fechas imposibles, sin CIRDOC raros")
doc12_lines.append("")
doc12_lines.append("### CLIENTE: tabla universal")
doc12_lines.append("")
doc12_lines.append("- 9,078 contactos, 215 campos (!), memo")
doc12_lines.append("- Usado para TODOS los roles: paciente, médico, hospital, obra social, vendedor, cliente comercial")
doc12_lines.append("- 9,077 códigos distintos")
doc12_lines.append("- 40 CLIENTEs aparecen en múltiples roles → múltiples ContactCompanyLink")
doc12_lines.append("- CLIATRI: 92,701 atributos EAV (AFIP, GLN, logística, etc.)")
doc12_lines.append("")
doc12_lines.append("### STOCK/STOCK1: el subsistema de remitos")
doc12_lines.append("")
doc12_lines.append("- STOCK: 9,754 headers, 36 campos")
doc12_lines.append("- STOCK1: 312,095 líneas, 55 campos, memo")
doc12_lines.append("- STKTIP A/B/C, STKES E/S, STKDEV S/N, STKCOM (11 valores)")
doc12_lines.append("- Patrón DEVOLUCIÓN-CONSUMO: 1,844 registros (STKDEV='S' + STKCONCE='DEVOLUCIÓN - CONSUMO')")
doc12_lines.append("- Patrón válido: 99.95%")
doc12_lines.append("- **Implicación OSSUM:** un Remito en OSSUM viene de un STOCK(STKCOM='RE'); un Devolucion viene del mismo STOCK visto desde la perspectiva del material retornado.")
doc12_lines.append("")
doc12_lines.append("### CUENTAS: facturación operacional")
doc12_lines.append("")
doc12_lines.append("- 22,055 facturas")
doc12_lines.append("- 56,021 líneas (CUENTASD)")
doc12_lines.append("- 17,595 facturas con VTACIRCOD FK (80%)")
doc12_lines.append("- Doble vínculo a CIRUGIA: VTACIRCOD directa + STKVTACOD via STOCK")
doc12_lines.append("- VTATIP A/B/C: tipo fiscal; VTACAI: CAE AFIP")
doc12_lines.append("- 99.5% de cirugías 2026 tienen al menos 1 factura")
doc12_lines.append("- Multi-factura por cirugía: hasta 11 (workflow de impresión/anulación)")
doc12_lines.append("")
doc12_lines.append("### Catálogos relevantes")
doc12_lines.append("")
doc12_lines.append("- VIAJANTE: 7 vendedores (incluido LETICIA TORRES que faltaba en muestra)")
doc12_lines.append("- CIRTIP: 75 tipos de cirugía (72 activos)")
doc03_lines_alt = []
doc03_lines_alt.append("- OBRAS: 11 obras sociales (catálogo INCOMPLETO vs 173 usadas en cirugías)")
doc03_lines_alt.append("- TRANSPOR: 68 transportistas")
doc03_lines_alt.append("- LOCALIDA: 1,236 localidades")
doc03_lines_alt.append("- PROVINCI: 25 provincias (Argentina)")
doc03_lines_alt.append("- SUCURSALES: 2 (Corrientes, Formosa)")
doc03_lines_alt.append("- MEDPAG: 26 medios de pago")
doc03_lines_alt.append("- CONDPAG: 8 condiciones de pago")
doc03_lines_alt.append("- ADMUSR: 27 usuarios del sistema")
doc03_lines_alt.append("- NUMERATO: 104 rangos de numeración")
doc03_lines_alt.append("- EMPRESA: 2 (PRINC = DISTRICORR SRL, TEST)")
for line in doc03_lines_alt:
    doc12_lines.append(line)
doc12_lines.append("")
doc12_lines.append("## Mapeo a OSSUM (resumen)")
doc12_lines.append("")
doc12_lines.append("| Legacy | OSSUM | Confianza |")
doc12_lines.append("|---|---|:---:|")
doc12_lines.append("| CIRUGIA | Surgery | ALTA |")
doc12_lines.append("| CLIENTE | Contact + ContactCompanyLink | ALTA |")
doc12_lines.append("| STOCK (RE) | Remito + RemitoItem | ALTA |")
doc12_lines.append("| STOCK1 (de RE) | RemitoItem | ALTA |")
doc12_lines.append("| STOCK (RE con STKDEV=S) | Devolucion + DevolucionItem | ALTA |")
doc12_lines.append("| CUENTAS | Invoice | ALTA |")
doc12_lines.append("| CUENTASD | InvoiceItem | ALTA |")
doc12_lines.append("| ARTICULO | Article | ALTA |")
doc12_lines.append("| ARTATRI | Article.metadata | MEDIA |")
doc12_lines.append("| CLIATRI | ContactCompanyLink.metadata | MEDIA |")
doc12_lines.append("| CIRNOTAS | Surgery.metadata.notes + extensión | MEDIA |")
doc12_lines.append("| HISCAM/HISCOS/HISPRE | AuditEvent / Article.metadata | MEDIA |")
doc12_lines.append("| FORMHIS/FORMULA1 | Article.metadata.formulaBOM | BAJA-MEDIA |")
doc12_lines.append("| ADMUSR | User | ALTA |")
doc12_lines.append("| HISREG/HISCON | descartar / metadata | BAJA |")
doc12_lines.append("| REPARTO | descartar | ALTA (no migrar) |")
doc12_lines.append("")
doc12_lines.append("## Riesgos principales")
doc12_lines.append("")
doc12_lines.append("### Riesgo 1: Multi-rol en CLIENTE")
doc12_lines.append("")
doc12_lines.append("- 40 CLIENTEs aparecen como paciente + médico, o paciente + payer, etc.")
doc12_lines.append("- OSSUM debe crear múltiples ContactCompanyLink (uno por rol)")
doc12_lines.append("- Mitigación: script de migración genera links por rol independiente")
doc12_lines.append("")
doc12_lines.append("### Riesgo 2: Contactos inactivos referidos")
doc12_lines.append("")
doc12_lines.append("- 190 referencias a CLIENTE con cliact='N'")
doc12_lines.append("- 87 médicos, 71 hospitales, 32 obras sociales")
doc12_lines.append("- Las cirugías que los usan siguen siendo válidas")
doc12_lines.append("- Mitigación: marcar el Contact como `isActive=false` en OSSUM, agregar flag `metadata.migratedFromInactiveLegacy=true`")
doc12_lines.append("")
doc12_lines.append("### Riesgo 3: Multi-factura por cirugía")
doc12_lines.append("")
doc12_lines.append("- Cirugías con 2-11 facturas (workflow de impresión/anulación)")
doc12_lines.append("- OSSUM debe decidir si importa todas o solo la 'última'")
doc12_lines.append("- Recomendación: importar todas, con metadata que indique orden temporal (vtafecemi)")
doc12_lines.append("- 4,729 facturas FIN 2026 con avg 3 líneas")
doc12_lines.append("")
doc12_lines.append("### Riesgo 4: Tablas con encoding corrupto")
doc12_lines.append("")
doc12_lines.append("- CUENTASD, otros: algunos chars 0x81/0x9d requieren `errors='replace'`")
doc12_lines.append("- Mitigación: usar errores='replace' en lectura, post-process OCR si es crítico")
doc12_lines.append("")
doc12_lines.append("### Riesgo 5: 'Devolución' semántica")
doc12_lines.append("")
doc12_lines.append("- El usuario asume que CAN/SUS/SCO crean devoluciones de stock")
doc12_lines.append("- El dataset muestra que NO — el sistema solo cambia estado")
doc12_lines.append("- Implicación: si OSSUM quiere generar devoluciones por cancelación, debe inferirlas (regla de negocio nueva) o aceptar que el material queda 'perdido' en el legacy")
doc12_lines.append("- Mitigación: documentar como brecha semántica y decidir caso por caso")
doc12_lines.append("")
doc12_lines.append("### Riesgo 6: REA vs FIN indistinguibles por facturas")
doc12_lines.append("")
doc12_lines.append("- Ambos tienen facturas similares")
doc12_lines.append("- Recomendación: usar CIRESTADO directamente, sin inferencia adicional")
doc12_lines.append("")
doc12_lines.append("### Riesgo 7: Volume")
doc12_lines.append("")
doc12_lines.append("- 2,577 cirugías × ~100 líneas de stock cada una = ~250K RemitoItems")
doc12_lines.append("- 4,729 facturas FIN × 3 líneas = ~14K InvoiceItems")
doc12_lines.append("- Total: ~300K registros a migrar")
doc12_lines.append("- Estimación: 2-4 horas de runtime si se hace cuidadoso, < 1 hora si se hace bulk")
doc12_lines.append("")
doc12_lines.append("## Recomendaciones operativas")
doc12_lines.append("")
doc12_lines.append("### Antes de la migración")
doc12_lines.append("")
doc12_lines.append("1. **Crear ledger transversal** (`LegacyEntityRef`) en OSSUM schema")
doc12_lines.append("2. **Crear `MigrationRun` + `MigrationError`** para tracking")
doc12_lines.append("3. **Verificar campos OSSUM necesarios** (Surgery.performedDate vs surgeryDate)")
doc12_lines.append("4. **Crear 2 Company OSSUM** (PRINC + TEST) y mapear EMPCOD")
doc12_lines.append("5. **Crear usuarios OSSUM** desde ADMUSR (27 usuarios)")
doc12_lines.append("6. **Crear grupos + permisos** desde ADMGRP/ADMGRP1/ADMMAP")
doc12_lines.append("")
doc12_lines.append("### Durante la migración")
doc12_lines.append("")
doc12_lines.append("1. **Contacto primero** (9,078 CLIENTE → 9,078 Contact + N×ContactCompanyLink)")
doc12_lines.append("2. **Artículos segundo** (5,902 ARTICULO → 5,902 Article)")
doc12_lines.append("3. **Catálogos** (VIAJANTE, CIRTIP, MEDPAG, etc.)")
doc12_lines.append("4. **Cirugías tercer** (7,512 CIRUGIA → 7,512 Surgery)")
doc12_lines.append("5. **Stock + Remitos + Devoluciones** (STOCK/STOCK1 → Remito/Devolucion/StockMovement)")
doc12_lines.append("6. **Facturas** (CUENTAS/CUENTASD → Invoice/InvoiceItem)")
doc12_lines.append("7. **Auditoría** (HISCAM/HISCOS → AuditEvent)")
doc12_lines.append("")
doc12_lines.append("### Después de la migración")
doc12_lines.append("")
doc12_lines.append("1. **Reconciliación**: query que compare totales legacy vs OSSUM")
doc12_lines.append("2. **Verificación huérfanos**: cirugías en OSSUM sin artículos, facturas sin contacto, etc.")
doc12_lines.append("3. **Reporte de discrepancias**: para revisión humana")
doc12_lines.append("4. **Snapshot del estado pre-migración** para auditoría")
doc12_lines.append("")
doc12_lines.append("## Próximos pasos sugeridos")
doc12_lines.append("")
doc12_lines.append("1. ✅ Esta auditoría (Fase 1-16)")
doc12_lines.append("2. ⏭️ Fase 17: leer análisis previo del agente Codex (E:\\OSSUM_COR_PROJECT\\docs\\migration-consultar-plus\\)")
doc12_lines.append("3. ⏭️ Fase 18: comparar y construir matriz Codex vs Minimax")
doc12_lines.append("4. ⏭️ Decisión: ¿hay cambios necesarios al schema OSSUM? (LegacyEntityRef, MigrationRun)")
doc12_lines.append("5. ⏭️ Diseñar scripts de migración (con ledger transversal, idempotencia)")
doc12_lines.append("6. ⏭️ Correr en DB DEV descartable")
doc12_lines.append("7. ⏭️ Validar con humanos")
doc12_lines.append("8. ⏭️ Commit local + PR")
doc12_lines.append("")
doc12_lines.append("## Honestidad final")
doc12_lines.append("")
doc12_lines.append("- Toda métrica en este análisis es reproducible (scripts en `scripts/legacy-minimax-audit/`)")
doc12_lines.append("- Ningún archivo del backup legacy fue modificado (verificado por timestamps)")
doc12_lines.append("- Ningún archivo OSSUM fue modificado")
doc12_lines.append("- Esta Fase 12 aún no leyó el análisis previo (E:\\OSSUM_COR_PROJECT\\docs\\migration-consultar-plus\\)")
doc12_lines.append("- Las conclusiones marcadas con ⚠️ requieren validación posterior")

(OUT_DIR / "12_CONCLUSIONES_FINALES.md").write_text("\n".join(doc12_lines), encoding="utf-8")
print("Wrote 12")
