-- AlterTable
ALTER TABLE "invoice_item" ADD COLUMN "vatTreatment" TEXT NOT NULL DEFAULT 'GRAVADO',
ADD COLUMN "vatRate" DECIMAL(18,4) NOT NULL DEFAULT 21.0000;

-- AlterTable
ALTER TABLE "presupuesto_item" ADD COLUMN "vatTreatment" TEXT NOT NULL DEFAULT 'GRAVADO',
ADD COLUMN "vatRate" DECIMAL(18,4) NOT NULL DEFAULT 21.0000;
