import { Prisma, type PrismaClient } from "@prisma/client";
import { createAuditEvent } from "../audit";
import { badRequest, conflict, notFound } from "../api/errors";
import { requireCompanyId } from "../tenant";

export const FACTURA_COMPRA_STATES = ["Pendiente", "Pagada", "Anulada"] as const;
export type FacturaCompraState = (typeof FACTURA_COMPRA_STATES)[number];
export const FACTURA_COMPRA_MUTATION_ROLES = ["admin", "coordinador", "logistica"] as const;
type Item = { stockItemId: string; name: string; code: string; quantity: string | number | Prisma.Decimal; unitPrice: string | number | Prisma.Decimal; descripcionLibre?: string | null };
type Base = { companyId: string; prisma: PrismaClient; updatedById?: string };
const select = { id: true, companyId: true, proveedorId: true, proveedorName: true, number: true, date: true, total: true, state: true, ordenCompraId: true, createdAt: true, pagadaAt: true, anuladaAt: true, observaciones: true, items: { select: { id: true, stockItemId: true, name: true, code: true, quantity: true, unitPrice: true, subtotal: true, descripcionLibre: true }, orderBy: { id: "asc" } } } satisfies Prisma.FacturaCompraSelect;
type Row = Prisma.FacturaCompraGetPayload<{ select: typeof select }>;
const decimal = (value: string | number | Prisma.Decimal) => (value instanceof Prisma.Decimal ? value : new Prisma.Decimal(value)).toDecimalPlaces(4, Prisma.Decimal.ROUND_HALF_UP);
const serialize = (row: Row) => ({ ...row, date: row.date.toISOString(), total: row.total.toString(), createdAt: row.createdAt.toISOString(), pagadaAt: row.pagadaAt?.toISOString() ?? null, anuladaAt: row.anuladaAt?.toISOString() ?? null, items: row.items.map((item) => ({ ...item, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), subtotal: item.subtotal.toString() })) });
export type FacturaCompraApi = ReturnType<typeof serialize>;
function items(values: Item[]) { if (!values?.length) throw badRequest("items must be a non-empty array", "factura_compra_empty_items"); return values.map((item, index) => { const quantity = decimal(item.quantity); const unitPrice = decimal(item.unitPrice); if (!item.stockItemId?.trim() || !item.name?.trim() || !item.code?.trim() || quantity.lte(0) || unitPrice.lt(0)) throw badRequest(`Invalid item ${index}`, "factura_compra_invalid_item"); return { stockItemId: item.stockItemId.trim(), name: item.name.trim(), code: item.code.trim(), quantity, unitPrice, subtotal: quantity.mul(unitPrice), descripcionLibre: item.descripcionLibre?.trim() || null }; }); }
const date = (value: string | Date) => { const parsed = value instanceof Date ? value : new Date(value); if (Number.isNaN(parsed.getTime())) throw badRequest("date must be a valid ISO date", "factura_compra_invalid_date"); return parsed; };
async function audit(prisma: PrismaClient | Prisma.TransactionClient, companyId: string, userId: string | undefined, id: string, action: string, oldValue: unknown, newValue: unknown) { if (userId) await createAuditEvent({ prisma: prisma as PrismaClient, companyId, userId, entityType: "FacturaCompra", entityId: id, action, module: "compras", oldValue, newValue }); }
async function current(tx: Prisma.TransactionClient, companyId: string, id: string) { await tx.$queryRaw`SELECT "id" FROM "FacturaCompra" WHERE "id" = ${id} AND "companyId" = ${companyId} FOR UPDATE`; const row = await tx.facturaCompra.findFirst({ where: { id, companyId }, select: { id: true, state: true } }); if (!row) throw notFound("FacturaCompra not found", "factura_compra_not_found"); return row; }
async function assertRelations(prisma: PrismaClient | Prisma.TransactionClient, companyId: string, proveedorId: string, ordenCompraId?: string | null) { const supplier = await prisma.contactCompanyLink.findFirst({ where: { companyId, contactId: proveedorId, isActive: true, OR: [{ roles: { has: "proveedor" } }, { role: "proveedor" }] }, select: { contactId: true } }); if (!supplier) throw badRequest("proveedorId must be an active supplier", "factura_compra_invalid_supplier"); if (ordenCompraId && !(await prisma.ordenCompra.findFirst({ where: { id: ordenCompraId, companyId }, select: { id: true } }))) throw badRequest("ordenCompraId must belong to the active company", "factura_compra_invalid_orden_compra"); }
export async function listFacturasCompra(input: Base & { state?: string; proveedorId?: string; ordenCompraId?: string; take?: number; skip?: number }) { const companyId = requireCompanyId(input.companyId); if (input.state && !FACTURA_COMPRA_STATES.includes(input.state as FacturaCompraState)) throw badRequest("Invalid state", "factura_compra_invalid_state_filter"); return (await input.prisma.facturaCompra.findMany({ select, where: { companyId, ...(input.state ? { state: input.state as FacturaCompraState } : {}), ...(input.proveedorId ? { proveedorId: input.proveedorId } : {}), ...(input.ordenCompraId ? { ordenCompraId: input.ordenCompraId } : {}) }, orderBy: { date: "desc" }, take: input.take ?? 100, skip: input.skip ?? 0 })).map(serialize); }
export async function getFacturaCompra(input: Base & { facturaCompraId: string }) { const row = await input.prisma.facturaCompra.findFirst({ select, where: { id: input.facturaCompraId, companyId: requireCompanyId(input.companyId) } }); if (!row) throw notFound("FacturaCompra not found", "factura_compra_not_found"); return serialize(row); }
export async function createFacturaCompra(input: Base & { proveedorId: string; proveedorName: string; number: string; date: string | Date; items: Item[]; ordenCompraId?: string | null; observaciones?: string | null; createdById?: string }) { const companyId = requireCompanyId(input.companyId); if (!input.proveedorId?.trim() || !input.proveedorName?.trim() || !input.number?.trim()) throw badRequest("Supplier and number are required", "factura_compra_invalid_input"); const normalized = items(input.items); await assertRelations(input.prisma, companyId, input.proveedorId, input.ordenCompraId); try { const row = await input.prisma.facturaCompra.create({ select, data: { companyId, proveedorId: input.proveedorId.trim(), proveedorName: input.proveedorName.trim(), number: input.number.trim(), date: date(input.date), total: normalized.reduce((sum, item) => sum.plus(item.subtotal), new Prisma.Decimal(0)), ordenCompraId: input.ordenCompraId || null, observaciones: input.observaciones?.trim() || null, items: { create: normalized } } }); await audit(input.prisma, companyId, input.createdById, row.id, "factura_compra_created", null, { state: row.state, total: row.total.toString() }); return serialize(row); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw conflict("A purchase invoice with this supplier and number already exists", "factura_compra_duplicate_number"); throw error; } }
export async function updateFacturaCompra(input: Base & { facturaCompraId: string; number?: string; date?: string | Date; items?: Item[]; ordenCompraId?: string | null; observaciones?: string | null }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.facturaCompraId); if (before.state !== "Pendiente") throw conflict("Only pending invoices can be edited", "factura_compra_not_pending"); const normalized = input.items ? items(input.items) : undefined; if (input.ordenCompraId !== undefined) await assertRelations(tx, companyId, "", input.ordenCompraId); const row = await tx.facturaCompra.update({ where: { id: before.id }, select, data: { ...(input.number !== undefined ? { number: input.number.trim() } : {}), ...(input.date !== undefined ? { date: date(input.date) } : {}), ...(normalized ? { items: { deleteMany: {}, create: normalized }, total: normalized.reduce((sum, item) => sum.plus(item.subtotal), new Prisma.Decimal(0)) } : {}), ...(input.ordenCompraId !== undefined ? { ordenCompraId: input.ordenCompraId || null } : {}), ...(input.observaciones !== undefined ? { observaciones: input.observaciones?.trim() || null } : {}) } }); await audit(tx, companyId, input.updatedById, row.id, "factura_compra_updated", { state: before.state }, { state: row.state }); return serialize(row); }); }
async function transition(input: Base & { facturaCompraId: string }, state: "Pagada" | "Anulada", stamp: "pagadaAt" | "anuladaAt", action: string) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.facturaCompraId); if (before.state !== "Pendiente") throw conflict("FacturaCompra is not pending", "factura_compra_not_pending"); const row = await tx.facturaCompra.update({ where: { id: before.id }, select, data: { state, [stamp]: new Date() } }); await audit(tx, companyId, input.updatedById, row.id, action, { state: before.state }, { state: row.state }); return serialize(row); }); }
export const registrarPagoFacturaCompra = (input: Base & { facturaCompraId: string }) => transition(input, "Pagada", "pagadaAt", "factura_compra_pagada");
export const cancelarFacturaCompra = (input: Base & { facturaCompraId: string }) => transition(input, "Anulada", "anuladaAt", "factura_compra_anulada");
export async function deleteFacturaCompra(input: Base & { facturaCompraId: string; deletedById?: string }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.facturaCompraId); if (before.state !== "Pendiente") throw conflict("Only pending invoices can be deleted", "factura_compra_not_pending"); await tx.facturaCompra.delete({ where: { id: before.id } }); await audit(tx, companyId, input.deletedById, before.id, "factura_compra_deleted", { state: before.state }, null); return { id: before.id, deleted: true as const }; }); }
