import { Prisma, type PrismaClient } from "@prisma/client";
import { createAuditEvent } from "../audit";
import { badRequest, notFound } from "../api/errors";
import { requireCompanyId } from "../tenant";

export const ORDEN_COMPRA_STATES = ["Borrador", "Emitida", "Enviada", "Parcialmente_recibida", "Recibida", "Cancelada"] as const;
export type OrdenCompraState = (typeof ORDEN_COMPRA_STATES)[number];
export const ORDEN_COMPRA_MUTATION_ROLES = ["admin", "coordinador", "logistica"] as const;
export const ORDEN_COMPRA_STATE_API_LABEL: Record<OrdenCompraState, string> = { Borrador: "Borrador", Emitida: "Emitida", Enviada: "Enviada", Parcialmente_recibida: "Parcialmente recibida", Recibida: "Recibida", Cancelada: "Cancelada" };
export class OrdenCompraError extends Error { constructor(readonly code: string, message: string, readonly status = 409) { super(message); } }

type Item = { stockItemId: string; name: string; code: string; quantity: string | number | Prisma.Decimal; unitPrice: string | number | Prisma.Decimal; isArticuloZ?: boolean; descripcionLibre?: string | null };
type Base = { companyId: string; prisma: PrismaClient; updatedById?: string };
const select = { id: true, companyId: true, proveedorId: true, proveedorName: true, total: true, state: true, emitidaAt: true, enviadaAt: true, recibidaAt: true, canceladaAt: true, observaciones: true, necesidadCompraIds: true, createdAt: true, items: { select: { id: true, stockItemId: true, name: true, code: true, quantity: true, unitPrice: true, subtotal: true, received: true, isArticuloZ: true, descripcionLibre: true }, orderBy: { id: "asc" } } } satisfies Prisma.OrdenCompraSelect;
type Row = Prisma.OrdenCompraGetPayload<{ select: typeof select }>;
const decimal = (v: string | number | Prisma.Decimal) => (v instanceof Prisma.Decimal ? v : new Prisma.Decimal(v)).toDecimalPlaces(4, Prisma.Decimal.ROUND_HALF_UP);
const serialize = (row: Row) => ({ ...row, total: row.total.toString(), stateLabel: ORDEN_COMPRA_STATE_API_LABEL[row.state], emitidaAt: row.emitidaAt?.toISOString() ?? null, enviadaAt: row.enviadaAt?.toISOString() ?? null, recibidaAt: row.recibidaAt?.toISOString() ?? null, canceladaAt: row.canceladaAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString(), items: row.items.map((item) => ({ ...item, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), subtotal: item.subtotal.toString(), received: item.received.toString() })) });
export type OrdenCompraApi = ReturnType<typeof serialize>;
function items(values: Item[]) { if (!values?.length) throw badRequest("items must be a non-empty array", "orden_compra_empty_items"); return values.map((item, index) => { const quantity = decimal(item.quantity); const unitPrice = decimal(item.unitPrice); if (!item.stockItemId?.trim() || !item.name?.trim() || !item.code?.trim() || quantity.lte(0) || unitPrice.lt(0)) throw badRequest(`Invalid item ${index}`, "orden_compra_invalid_item"); return { stockItemId: item.stockItemId.trim(), name: item.name.trim(), code: item.code.trim(), quantity, unitPrice, subtotal: quantity.mul(unitPrice), received: new Prisma.Decimal(0), isArticuloZ: !!item.isArticuloZ, descripcionLibre: item.descripcionLibre?.trim() || null }; }); }
async function audit(prisma: PrismaClient | Prisma.TransactionClient, companyId: string, userId: string | undefined, id: string, action: string, oldValue: unknown, newValue: unknown) { if (userId) await createAuditEvent({ prisma: prisma as PrismaClient, companyId, userId, entityType: "OrdenCompra", entityId: id, action, module: "compras", oldValue, newValue }); }
async function current(tx: Prisma.TransactionClient, companyId: string, id: string) { await tx.$queryRaw`SELECT "id" FROM "OrdenCompra" WHERE "id" = ${id} AND "companyId" = ${companyId} FOR UPDATE`; const row = await tx.ordenCompra.findFirst({ where: { id, companyId }, select: { id: true, companyId: true, state: true, items: { select: { id: true, quantity: true, received: true } } } }); if (!row) throw notFound("OrdenCompra not found", "orden_compra_not_found"); return row; }
export async function listOrdenesCompra(input: Base & { state?: string; proveedorId?: string; take?: number; skip?: number }) { const companyId = requireCompanyId(input.companyId); if (input.state && !ORDEN_COMPRA_STATES.includes(input.state as OrdenCompraState)) throw badRequest("Invalid state", "orden_compra_invalid_state_filter"); return (await input.prisma.ordenCompra.findMany({ select, where: { companyId, ...(input.state ? { state: input.state as OrdenCompraState } : {}), ...(input.proveedorId ? { proveedorId: input.proveedorId } : {}) }, orderBy: { createdAt: "desc" }, take: input.take ?? 100, skip: input.skip ?? 0 })).map(serialize); }
export async function getOrdenCompra(input: Base & { ordenCompraId: string }) { const row = await input.prisma.ordenCompra.findFirst({ select, where: { id: input.ordenCompraId, companyId: requireCompanyId(input.companyId) } }); if (!row) throw notFound("OrdenCompra not found", "orden_compra_not_found"); return serialize(row); }
export async function createOrdenCompra(input: Base & { proveedorId: string; proveedorName: string; items: Item[]; observaciones?: string | null; necesidadCompraIds?: string[]; createdById?: string }) { const companyId = requireCompanyId(input.companyId); if (!input.proveedorId?.trim() || !input.proveedorName?.trim()) throw badRequest("Supplier is required", "orden_compra_invalid_supplier"); const normalized = items(input.items); const total = normalized.reduce((sum, item) => sum.plus(item.subtotal), new Prisma.Decimal(0)); const row = await input.prisma.ordenCompra.create({ select, data: { companyId, proveedorId: input.proveedorId.trim(), proveedorName: input.proveedorName.trim(), total, observaciones: input.observaciones?.trim() || null, necesidadCompraIds: input.necesidadCompraIds?.filter(Boolean) ?? [], items: { create: normalized } } }); await audit(input.prisma, companyId, input.createdById, row.id, "orden_compra_created", null, { state: row.state, total: row.total.toString() }); return serialize(row); }
export async function updateOrdenCompra(input: Base & { ordenCompraId: string; items?: Item[]; observaciones?: string | null; necesidadCompraIds?: string[] }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.ordenCompraId); if (before.state !== "Borrador") throw new OrdenCompraError("orden_compra_not_editable", "Only draft purchase orders can be edited"); const normalized = input.items ? items(input.items) : undefined; const row = await tx.ordenCompra.update({ where: { id: before.id }, select, data: { ...(normalized ? { items: { deleteMany: {}, create: normalized }, total: normalized.reduce((sum, item) => sum.plus(item.subtotal), new Prisma.Decimal(0)) } : {}), ...(input.observaciones !== undefined ? { observaciones: input.observaciones?.trim() || null } : {}), ...(input.necesidadCompraIds ? { necesidadCompraIds: input.necesidadCompraIds.filter(Boolean) } : {}) } }); await audit(tx, companyId, input.updatedById, row.id, "orden_compra_updated", { state: before.state }, { state: row.state }); return serialize(row); }); }
async function transition(input: Base & { ordenCompraId: string }, from: OrdenCompraState, to: OrdenCompraState, action: string, stamp: "emitidaAt" | "enviadaAt") { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.ordenCompraId); if (before.state !== from || (from === "Borrador" && !before.items.length)) throw new OrdenCompraError("orden_compra_invalid_transition", `Cannot transition from ${before.state}`); const row = await tx.ordenCompra.update({ where: { id: before.id }, select, data: { state: to, [stamp]: new Date() } }); await audit(tx, companyId, input.updatedById, row.id, action, { state: before.state }, { state: row.state }); return serialize(row); }); }
export const emitirOrdenCompra = (input: Base & { ordenCompraId: string }) => transition(input, "Borrador", "Emitida", "orden_compra_emitida", "emitidaAt");
export const enviarOrdenCompra = (input: Base & { ordenCompraId: string }) => transition(input, "Emitida", "Enviada", "orden_compra_enviada", "enviadaAt");
export async function recibirOrdenCompra(input: Base & { ordenCompraId: string; receivedByItem?: { itemId: string; received: string | number }[] }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.ordenCompraId); if (!["Enviada", "Parcialmente_recibida"].includes(before.state)) throw new OrdenCompraError("orden_compra_not_receivable", "Purchase order is not receivable"); for (const update of input.receivedByItem ?? []) { const item = before.items.find((value) => value.id === update.itemId); const quantity = decimal(update.received); if (!item || quantity.lt(0) || item.received.plus(quantity).gt(item.quantity)) throw new OrdenCompraError("orden_compra_invalid_receipt", "Invalid receipt quantity"); await tx.ordenCompraItem.update({ where: { id: item.id }, data: { received: item.received.plus(quantity) } }); } const refreshed = await tx.ordenCompraItem.findMany({ where: { ordenCompraId: before.id }, select: { quantity: true, received: true } }); const done = refreshed.every((item) => item.received.gte(item.quantity)); const row = await tx.ordenCompra.update({ where: { id: before.id }, select, data: { state: done ? "Recibida" : "Parcialmente_recibida", recibidaAt: done ? new Date() : null } }); await audit(tx, companyId, input.updatedById, row.id, "orden_compra_recibida", { state: before.state }, { state: row.state }); return serialize(row); }); }
export async function cancelarOrdenCompra(input: Base & { ordenCompraId: string; motivo?: string }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.ordenCompraId); if (["Recibida", "Cancelada"].includes(before.state)) throw new OrdenCompraError("orden_compra_invalid_cancel_transition", "Purchase order cannot be cancelled"); const row = await tx.ordenCompra.update({ where: { id: before.id }, select, data: { state: "Cancelada", canceladaAt: new Date() } }); await audit(tx, companyId, input.updatedById, row.id, "orden_compra_cancelada", { state: before.state }, { state: row.state, motivo: input.motivo ?? null }); return serialize(row); }); }
export async function deleteOrdenCompra(input: Base & { ordenCompraId: string; deletedById?: string }) { const companyId = requireCompanyId(input.companyId); return input.prisma.$transaction(async (tx) => { const before = await current(tx, companyId, input.ordenCompraId); if (before.state !== "Borrador") throw new OrdenCompraError("orden_compra_not_deletable", "Only drafts can be deleted"); await tx.ordenCompra.delete({ where: { id: before.id } }); await audit(tx, companyId, input.deletedById, before.id, "orden_compra_deleted", { state: before.state }, null); return { id: before.id, deleted: true as const }; }); }
